### ISSUE TITLE
INSPIRE GEOPORTAL doesn`t recognize SDI Digital certificate- SPAIN

### ISSUE THREAD

**Issue by MarisolGomezAndres** [INSPIRE-MIF/helpdesk-validator#581] opened 2021-07-09 11:03 UTC
There is a problem in recognising our SDI certificate from FNMyT as a valid Authorisation Entity and that´s the reason by our metadata and services are not validated and visualized in the INSPIRE Geoportal. Therefore, the FNMyT Certification Authoritie shoud be included as a valid Authorisation Entity. We have analysed the validation errors and discover that  the **Geoportal INSPIRE  doesn´t recognise our certificate.** The same error has happened in the past for at least one year.

**Comment by MarcoMinghini** [comment] 2021-07-09 14:03
Dear @MarisolGomezAndres,
can you please clarify what the issue is? This is the helpdesk of the INSPIRE Reference Validator, and the Validator has no influence on whether datasets are/are not visualised in the INSPIRE Geoportal.

If the problem is with the INSPIRE Geoportal, you should open an issue in the [Geoportal helpdesk](https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/). It might be that the issue has not been fixed in the Geoportal because you have not opened a ticket there.

As far as I can see, all the previous issues reported in this helpdesk (Validator) were successfully solved (see e.g. https://github.com/INSPIRE-MIF/helpdesk-validator/issues/471 and https://github.com/INSPIRE-MIF/helpdesk-validator/issues/543).

**Comment by MarisolGomezAndres** [comment] 2021-07-09 15:55
Dear Marco:

I just open a new issue in the Geoportal Helpdesk.

https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/48

Best regards.

Marisol Gómez Andrés
Information Technology and Communication Department
Web and GIS services Manager

De: Marco Minghini ***@***.***
Enviado el: viernes, 9 de julio de 2021 16:04
Para: INSPIRE-MIF/helpdesk-validator ***@***.***>
CC: Gómez Andrés, Soledad ***@***.***>; Mention ***@***.***>
Asunto: [MAIL_EXTERNO] Re: [INSPIRE-MIF/helpdesk-validator] INSPIRE GEOPORTAL doesn`t recognize SDI Digital certificate- SPAIN (#581)


Dear @MarisolGomezAndres<https://github.com/MarisolGomezAndres>,
can you please clarify what the issue is? This is the helpdesk of the INSPIRE Reference Validator, and the Validator has no influence on whether datasets are/are not visualised in the INSPIRE Geoportal.

If the problem is with the INSPIRE Geoportal, you should open an issue in the Geoportal helpdesk<https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/>. It might be that the issue has not been fixed in the Geoportal because you have not opened a ticket there.

As far as I can see, all the previous issues reported in this helpdesk (Validator) were successfully solved (see e.g. #471<https://github.com/INSPIRE-MIF/helpdesk-validator/issues/471> and #543<https://github.com/INSPIRE-MIF/helpdesk-validator/issues/543>).

**Comment by MarcoMinghini** [comment] 2021-07-14 08:13
Dear @MarisolGomezAndres,
we close this issue as the problem seems not to be on the Validator. We checked again the metadata from your previous issues and they are correctly validated. Feel free to re-open the issue, should you encounter any new problem.

**Closed as completed by MarcoMinghini** 2021-07-14 08:13 UTC
