### ISSUE TITLE
Inspire validator doesn´t work

### ISSUE THREAD

**Issue by laralpz** [INSPIRE-MIF/helpdesk-validator#744] opened 2022-04-11 11:44 UTC
I need to validate an xml file with the following options:
Metadata
Version 2.0
Spatial Data Service

But when I try to upload the file. An error occurs:
ERROR
An error occurred while uploading the file (Code: 400 - Bad Request)
It's been failing for a few days, I'm afraid it's a general error. When could it be fixed?

**Comment by jenriquesoriano** [comment] 2022-04-11 13:04
Dear  @laralpz 

thank you for contacting us and reporting this issue.
We are working on its diagnosis and resolution. 
On the other hand, it is useful for us that you provide us with the metadata with which the issue is occurring, so if you could attach it to the issue, it would be very much appreciated.

Best regards,

**Comment by laralpz** [comment] 2022-04-11 13:21
Dear @jenriquesoriano 
 I'm afraid the metadata has no relation to the problem but here it is. I ´ve changed the file extension from xml to txt to let me upload it.
[Ejemplo castellano.txt](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8464396/Ejemplo.castellano.txt)
Regards

**Comment by arantzaetxebarria** [comment] 2022-04-12 10:33
Dear @laralpz 

We have tested your metadata sample, and it seems that the schema of the metadata is not well conformed.
Maybe, this other [Dataset_metadata_2.0_example_.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8472078/Dataset_metadata_2.0_example_.zip) can help you, it works properly and is processed by the validator.

Regards,

Arantza

**Comment by laralpz** [comment] 2022-04-12 10:36
Dear @arantzaetxebarria ,
Thanks a lot, I am going to revise it
Kind regards,
Lara

**Comment by arantzaetxebarria** [comment] 2022-04-12 11:12
Dear @laralpz 

We will close this issue. Please feel free to open a new one if needed.

Regards

**Closed as completed** 2022-04-12 11:13 UTC
