### ISSUE TITLE
gmd:CI_DateTypeCode  and GMX issue

### ISSUE THREAD

**Issue by dlutsVMM** [INSPIRE-MIF/helpdesk-validator#106] opened 2019-09-04 13:58 UTC
I am finally going to ask about two issues I repeatedly get when trying to validate metadata created using newer versions of geonetwork (currently I am using geonetwork 3.6.0).

In Geonetwork I have added the GEMET - INSPIRE themes thesaurus using Re3gistry.
When I then try to validate the exported xml-metadata file, I each time get a fail for the dataset keyword test. It points out that the gmd:CI_DateTypeCode is empty, but when I inspect the xml I find that gmd:CI_DateTypeCode is filled in with "publication" as described in the TG. The only way I have found to fix the metadata and get it through the validator succesfully is by just copying the whole block from another XML file I know does validate correctly.

Any suggestions about this topic?

[testreporthtml.docx](https://github.com/inspire-eu-validation/community/files/3574834/testreporthtml.docx)

[3c3e9731-819a-4ad6-8635-ac9ef52d6b2f.docx](https://github.com/inspire-eu-validation/community/files/3574815/3c3e9731-819a-4ad6-8635-ac9ef52d6b2f.docx)

The second issue is detailed in issue 107

**Comment by josemasensio** [comment] 2019-09-05 06:28
Dear @dlutsVMM,

Thank you for your message. 

For the first question, please, could you specify what test you are doing? And can you provide the XML that validates correctly?

For the second question, we are checking on it. We will came back with a solution as soon as we get one.

Best regards.

**Comment by dlutsVMM** [comment] 2019-09-05 06:36
Dear Josemasensio,

I am running both test from Metadata (TG version 1.3).

In the attached zip you can find a xml file that validates correctly for me.

[metadata_PRTR_02_6.zip](https://github.com/inspire-eu-validation/community/files/3577772/metadata_PRTR_02_6.zip)

**Comment by josemasensio** [comment] 2019-09-05 09:34
Thanks, we will come back to you with a solution. 

Best regards .

**Comment by josemasensio** [comment] 2019-09-05 10:12
Dear @dlutsVMM,

We have checked your XML and there is an issue on the gmd:CI_DateTypeCode. 

The thing is that you are closing it without value. You can see [here](https://github.com/inspire-eu-validation/community/blob/master/examples/Dataset_metadata_2.0_example#L109) that is necessary the value of gmd:CI_DateTypeCode. This happend along the XML.

Best regards.

**Comment by josemasensio** [comment] 2019-09-05 10:17
@dlutsVMM 
Please, could you modify this issue deleting the second part of it and creating a new issue with that second part? We will appreciate it.

Greetings

**Comment by dlutsVMM** [comment] 2019-09-05 10:32
Dear Jose, 

If you look at the xml in the zip, you will see that this is not the case. But, this xml does get through the validator while the one of my question does not. 

The second problem is that Geonetwerk automatically changes 
<gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="creation">Creation</gmd:CI_DateTypeCode>

to 
<gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="creation"/>

when you save the xml.

While I know I sometimes can solve the issue by declaring the value explicitly but I do not think that is the actual solution or reason why the test is failing because sometimes an xml which closes without a value does also get through.

I'll make a new issue for the second part.

Thanks already for your effort.

**Comment by josemasensio** [comment] 2019-09-05 10:52
Dear @dlutsVMM 

As you said the metadata xml you sent to us is correct. The issue resides in the use of Geonetwork, you could find a solution in the new INSPIRE Community Forum, where there is a dedicated section on Software & Tools: https://inspire.ec.europa.eu/forum/tcc and you may also open an issue in the GeoNetwork helpdesk on GitHub.

If we can help you in anything else let us know.

**Comment by dlutsVMM** [comment] 2019-09-05 11:16
Jose, I get that this is partly a Geonetwerk issue (the it removes the explicit value part). What I do not get is why the xml file in the zip files gets through the validator and the xml in the docx in my orginal issue-post does not. That seems to me either a validator issue or somehow a difference (which I can't see) that has been introduced in both files. This is where I ask your help with. The other part I will raise at the inspire community forum.

**Comment by josemasensio** [comment] 2019-09-05 11:26
Dear @dlutsVMM 

The issue is in the CI_DateTypeCode that in the file from the zip has a value and in the docx file has no value.

- metadata_PRTR_02_6.zip
<gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode"
                                                   codeListValue="publication">****publication**</gmd:CI_DateTypeCode>**

- 3c3e9731-819a-4ad6-8635-ac9ef52d6b2f.docx
<gmd:CI_DateTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_DateTypeCode"
                                                   codeListValue="publication"/>

As you can see above, the value in bold for the zip file is missing in the docx file.

**Comment by dlutsVMM** [comment] 2019-09-05 11:57
[1ed5e09b-85d6-4601-b040-edf9305d8339(1).zip](https://github.com/inspire-eu-validation/community/files/3579147/1ed5e09b-85d6-4601-b040-edf9305d8339.1.zip)

Jose, my apologies for giving you the wrong file for illustrating my issue.
So now in this zip file, an xml that should better illustrate my issue.

**Comment by josemasensio** [comment] 2019-09-05 12:30
Dear @dlutsVMM 

The validation is looking for the value of the element CI_DateTypeCode when the thesaurusName title is equal to 'GEMET - INSPIRE themes, version 1.0'. In the provided file that passess the validation you do not have that title, instead you have 'GEMET - INSPIRE thema's, versie 1.0'. Other thing we have checked in the wrong file is that the xml headers are raising an error I suggest you to use the ones in the correct file.

**Comment by dlutsVMM** [comment] 2019-09-05 12:44
Hi, Jose thank you for finding this. So to be clear both files are actually incorrect, but for 1ed5e09b-85d6-4601-b040-edf9305d8339(1) this is not showing up in the validator because the title for the INSPIRE themes is in dutch instead of english?

About the headers, which file is raising errors? Where do you see this (so that I can detect the min the future)?

**Comment by josemasensio** [comment] 2019-09-06 07:26
Dear @dlutsVMM,

Yes, the validator right now checks if the title is only 'GEMET - INSPIRE themes, version 1.0'. Maybe this should be modified to check every title. We will discuss about this and we will come back to you when a decission is taken.

Best regards.

**Comment by MarcoMinghini** [comment] 2019-09-17 13:37
Dear @dlutsVMM, 

the name of the thesaurus should not be expressed in national languages, although the MD TG v.1.3 do not state this explicitly (but they also do not state that it can be expressed in any national language).

Instead, Requirement 1.4 of MD TG v.2.0 clearly specifies the exact value of the string of the `gmd:title` element:

> The value of the gmd:thesaurusName/gmd:CI_Citation/gmd:title element shall contain value "GEMET - INSPIRE themes, version 1.0".

Therefore:

1) the test for MD TG v.1.3 should be fixed as follows: the Validator should check that at least one keyword from the GEMET thesaurus is present, which means checking for the exact string "GEMET - INSPIRE themes, version 1.0". If no occurrence is found, an error should be raised (because this means that no spatial data theme is declared for the metadata). In addition, the Validator should check that the value of the element `gmd:CI_DateTypeCode` is not empty. 

2) note that data providers should only provide MD compliant to the TG v.2.0 starting from December 2019 (see the following text from MD TG v.2.0):

> To facilitate a smooth transition from version 1.3 to version 2.0, a transitional period of 3 years has been defined, starting from 19 December 2016. During this period, the metadata records compliant with both version 1.3 and 2.0 implementations will be considered as “compliant with the INSPIRE Technical Guidelines for Metadata”. During the transitional period, the validator used in the INSPIRE geoportal will validate against and will provide validation reports for both versions 1.3 and 2.0. The better result will be used for the value of the compliance meter. After the transitional period, the geoportal will only validate against version 2.0.

For this reason, support for validation of MD TG v.1.3 will end soon. Therefore, you are encouraged to change your metadata to make it compliant to TG v.2.0.

**Comment by dlutsVMM** [comment] 2019-09-17 14:11
Hi Marco,

Thanks for the response. This gives me at least some clarification about the issue and TG v.2.0 (something I wanted to query our national Inspire POC about).

One remark at the moment I was a bit confused about whether 2.0 was already in full use because when I go on the INSPIRE site to the TG for the metadata, none of the document titles mention that they are about v.2.0 (in hindsight I should have looked a bit further). Maybe a clarification in the titles can help that the TG v.1.3 is followed by the TG v.2.0 document (now called: Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007).

**Comment by josemasensio** [comment] 2019-10-17 15:28
Dear @dlutsVMM,

We just applied the changes that @MarcoMinghini mentioned above on the staging environment. Please, can you check it?

Best regards.

**Comment by dlutsVMM** [comment] 2019-10-18 08:29
This appears to have solved the issue, thanks!

**Comment by josemasensio** [comment] 2019-10-18 08:35
Dear @dlutsVMM,

Glad to hear that. I will mark the issue as solved. 

Greetings.

**Closed as completed** 2019-11-19 10:50 UTC
Labels: deployed in reference validator
