### ISSUE TITLE
Problem to validate direct WFS service

### ISSUE THREAD

**Issue by vicehovskis** [INSPIRE-MIF/helpdesk-validator#447] opened 2020-11-16 11:10 UTC
There is a problem to validate Download Service - Direct WFS -> every time is received "Uknown error".

Tried to validate this WFS link -> https://grafws.kadastrs.lv/geoserver/ad/Address/ows?service=WFS&version=2.0.0&request=GetCapabilities 

Using Chrome browser, version 86.0.4240.193 

<img width="790" alt="2020-11-16_13h08_47" src="https://user-images.githubusercontent.com/56715045/99245916-17910d00-280d-11eb-8522-c5d04a24ecd3.png">

**Comment by carlospzurita** [comment] 2020-11-16 12:23
Dear @vicehovskis 

It seems that the service is not responding to any request on our side. This may be the cause of this initialization error. Please check out the status of the service.

**Comment by vicehovskis** [comment] 2020-11-16 12:32
@carlospzurita This service is available in public. From which IP addresses validator make requests?

**Comment by carlospzurita** [comment] 2020-11-16 12:41
Now we were able to get a response from the service, and the Test Run is created both on the [reference validator](https://inspire.ec.europa.eu/validator/) and on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/), so it seems that this may be due to a momentary problem on the service.

**Comment by vicehovskis** [comment] 2020-11-16 13:24
@carlospzurita  now error is not received, but still can`t get validation results. 

<img width="903" alt="2020-11-16_15h20_24" src="https://user-images.githubusercontent.com/56715045/99257549-e0782700-281f-11eb-9825-661a9765858a.png">

**Comment by carlospzurita** [comment] 2020-11-16 14:13
This test has a dependency on the OGC TEAM engine, as you can see on the dialog. This is managed through a request to the remote API offered by the OGC, and has a timeout of 20 minutes. If the TEAM engine takes more time to respond then the test is marked as skipped, as you can see in [this report ](https://inspire.ec.europa.eu/validator/v2/TestRuns/EID9bb4c2c2-a210-4699-8408-30ad94f021c4.html). The test does work on the staging instance (see [report](staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDbbab0e9d-1e47-4ab7-9870-4e3b870ca771.html)) which uses the beta API from the OGC, so we are trying to see if this is a problem located on the production version of the TEAM engine.

**Comment by vicehovskis** [comment] 2020-11-17 08:02
Still can`t get the Test report..  I receive the same message all the time -> "Connection to test runner lost. The test could have been canceled without generating  a report or the internet connection to the web application has been lost!"

**Comment by carlospzurita** [comment] 2020-11-18 13:16
The service is now unable to be executed on the TEAM engine. If you perform this request https://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.34/run?wfs=https://grafws.kadastrs.lv/geoserver/ad/Address/ows?service=WFS%26version=2.0.0%26request=GetCapabilities you will get an error for a malformed XML. The monitor of the TestRun gets this exception and throw the error for the"Connection lost", but the test is executed and generates a partially executed TestReport https://inspire.ec.europa.eu/validator/v2/TestRuns/EID90bb6a07-09e0-4f2a-a2a4-2f34c3712921.html

**Comment by carlospzurita** [comment] 2021-05-21 10:18
Dear @vicehovskis 

Did you retried to validate your service? Is the issue still present?

Kind regards.

**Comment by dperezBM** [comment] 2021-08-19 10:53
Dear @vicehovskis,

Is this issue still present?

Best regards.

**Comment by fabiovin** [comment] 2021-08-25 09:19
Dear @vicehovskis,

it seems that the tested WFS is no longer available, so let’s close the issue.

Please reopen it, or open a new one, if the problem persists.

Thanks,
Fabio

**Closed as completed by fabiovin** 2021-08-25 09:19 UTC
