### ISSUE TITLE
The timeout was exceeded

### ISSUE THREAD

**Issue by DLList** [INSPIRE-MIF/helpdesk-validator#166] opened 2019-11-25 14:44 UTC
Hello,

I have a problem with the ETF-Validator that I'd like to solve here.

I am currently busy developing a tool for transforming street data into INSPIRE Transport Network Structures. I have created several INSPIRE Features and tested them with the Validator. I have a problem with the error message "The timeout was exceeded".

**My approach for creating INSPIRE-Data**
Creating a normal GML file with INSPIRE objects (INSPIRE Transport Network)

**Testing the DataSet with the Validator**
No error is thrown for smaller files. For a large file (500 MB) the following error is thrown during testing: "The timeout was exceeded" (Conformance Class: INSPIRE GML application schemas, General requirements => Schema validation).

![Timeout](https://user-images.githubusercontent.com/49745407/69549666-fef36b80-0f99-11ea-8296-511c621867d6.png)

**Question**
My question is: Where does this error message come from and how can it be fixed??

Best regards,
Dawid

PS. I can't send the test data because it can't be published yet.

**Comment by josemasensio** [comment] 2019-11-26 11:31
Dear @DLList,

Please, in order to reproduce the error on our environment, would you mind to provide us with the data by email sending them to inspire-helpdesk@bilbomatica.com. All data sent to this address will be completely confidential and will only be used in order to improve the validator. Once the issue has been solved all data will be deleted.

Thank you and best regards.

**Comment by josemasensio** [comment] 2019-12-03 08:08
Dear @DLList,

Please, in order to reproduce the error on our environment, would you mind to provide us with the data by email sending them to inspire-helpdesk@bilbomatica.com. All data sent to this address will be completely confidential and will only be used in order to improve the validator. Once the issue has been solved all data will be deleted.

Thank you and best regards.

**Comment by josemasensio** [comment] 2019-12-09 10:30
Dear @DLList 

Without your feedback, we could not proceed to fix the issue. We will be waiting for a week, but if there is no feedback, we will close the issue.
Thanks for understanding.

Best regards.

**Comment by DLList** [comment] 2019-12-10 07:44
Dear @josemasensio,

thank you first for the answer. I sent the answer about the data to my boss and wait for an answer in this topic. I can't send you the data until he allow me this. 
I hope there's no hurry for you.

Many thanks and best regards.

**Comment by JohannaOtt** [comment] 2020-04-01 11:14
I get the same error message for test ID EID0eaac0f2-9ab3-44ab-9f02-4ee0a1587d14. This is the log http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDfae73f97-40f6-4550-9c59-3a87dc221978/log.
In case you need example data, I would need to clarify with the customer the data belongs to, if it can be shared.

**Comment by dperezBM** [comment] 2021-05-04 21:01
Dear @JohannaOtt , @DLList ,

With the intention to resume this problem, could you please confirm that the error is still occurring? And if so, could you please send us the files that are failing?

Thank you very much in advance.

Best regards

**Comment by JohannaOtt** [comment] 2021-05-05 05:59
I am sorry, but I cannot retrace which file this occurred for back then. I also cannot find the ID "0eaac0f2-9ab3-44ab-9f02-4ee0a1587d14" in the ets GitHub repository, so I do not know what kind of test it was.

**Comment by carlospzurita** [comment] 2021-05-18 12:09
Dear @JohannaOtt 

If it is helpful, this issue appeared originally validating a large GML file, for the test `Conformance Class: INSPIRE GML application schemas, General requirements `. We would try to retrace the problem, but if you happen to find the file please let us know.

**Comment by fabiovinci** [comment] 2023-03-21 17:33
Dear all,
since there was no reply from your side, I will close the issue.
Please reopen it or open a new issue if the error persists.

**Closed as completed by fabiovinci** 2023-03-21 17:33 UTC
