### ISSUE TITLE
Predefined WFS Validation - URL problem

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-validator#22] opened 2019-02-01 13:29 UTC
Dear INSPIRE Validation Team,

I hope you can help me with my following validation problem:

I wanted to start a validation with the ETF Validator of our INSPIRE WFS servcie with the URL https://gis.bmnt.gv.at/wmsgw/?key=a64a0c9c9a692ed7041482cb6f03a40a&REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0

But the validation fails already with the first test. As you can see our service needs the parameter "key" to linke the service request to the correct GeoServer. The ETF Validator somehow "shortens" the URL and tries to retrieve the URL https://gis.bmnt.gv.at/wmsgw/?ACCEPTVERSIONS=2.0.0&REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0 (instead of https://gis.bmnt.gv.at/wmsgw/?key=a64a0c9c9a692ed7041482cb6f03a40a&ACCEPTVERSIONS=2.0.0&REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0 which would work).

Is it possible to tell the validator that the endpoint is not https://gis.bmnt.gv.at/wmsgw/ but https://gis.bmnt.gv.at/wmsgw/?key=a64a0c9c9a692ed7041482cb6f03a40a

Validation report: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestRuns/EID7492bf18-45bb-4e61-96e6-445a8161afc9.html

Thanks in advance,
Manuel

**Comment by fabiovinci** [comment] 2023-02-20 12:23
Dear all,

we will close the issue since it seems the services are no more available.

**Closed as completed by fabiovinci** 2023-02-20 12:23 UTC
Labels: for-2017.4-discussion

**Comment by nmtoken** [comment] 2023-02-20 12:49
Only one service was ever available, the other was a dummy  to ask about allowed structure.   i.e. does the validator strip off all parameters past the "?"  prior to formulating its own request? If so there is still an issue

**Comment by fabiovinci** [comment] 2023-02-20 13:15
@nmtoken,
do you have an example to reproduce the error?

**Comment by nmtoken** [comment] 2023-02-20 13:51
Can't you test by getting any known WFS, adding a random parameter like 'map=service-config.map&' and seeing if that parameter is kept by the validator?
