### ISSUE TITLE
Pre-defined WFS partially skipped for unknown reason

### ISSUE THREAD

**Issue by thijsbrentjens** [INSPIRE-MIF/helpdesk-validator#38] opened 2019-04-24 13:07 UTC
The reference validator can't run all tests of the Pre-defined WFS testsuite for this specific WFS implementation: https://geodata.nationaalgeoregister.nl/inspire/su-grid/wfs?ACCEPTVERSIONS=2.0.0&REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0

The same behavior in the staging as in the current production environment.

It is unclear why the tests can't be run completely. This step fails: Initialization and basic checks > Autoconfigure WFS > Analyze WFS Capabilities. But both checks of Analyze WFS Capabilities are passed (successfully). 

What is the reason this service fails? Could it be that the request for hits returns 0 as the number of hits? If so, could the report be updated to reflect this? It is hard to find out what is not working correctly.

-- 
To help us investigate the issue, you may want to include:
- [x] a description of the steps to reproduce your issue
1. select Pre-defined WFS and start the test
2. use this URL of the service: https://geodata.nationaalgeoregister.nl/inspire/su-grid/wfs?
3. see the report, step: Initialization and basic checks > Autoconfigure WFS > Analyze WFS Capabilities

- [x] a screenshot illustrating the problem

![autconfigure_su_grid_wfs](https://user-images.githubusercontent.com/1172941/56661608-67940600-66a2-11e9-9547-dcf2e07dc0ca.png)

- [x] the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDe7f0f234-b4ac-42b1-87f9-80d49c6a275f.html?lang=nl#EID4f5ebfa8-016a-1000-f320-15366935667a

- [x] the URL of your service / the file you have uploaded or referenced (as
an attachment).:  https://geodata.nationaalgeoregister.nl/inspire/su-grid/wfs?ACCEPTVERSIONS=2.0.0&REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0

**Comment by thijsbrentjens** [comment] 2019-04-24 13:14
Another WFS implementation where the reason of skipping the tests is not clear: 
https://inspire.caris.nl/server/services/ows/download/feature/tz-gebieden_IDS?ACCEPTVERSIONS=2.0.0&REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0

**Comment by thijsbrentjens** [comment] 2019-11-25 14:20
For analyzing something else, I ran into this issue again. And found something that may help in a fix. The service https://geodata.nationaalgeoregister.nl/inspire/su-grid/wfs?  does not seem to return the correct number of features when requesting the hits only, so for this request:

https://geodata.nationaalgeoregister.nl/inspire/su-grid/wfs?REQUEST=GetFeature&RESULTTYPE=hits&OUTPUTFORMAT=text%2Fxml%3B%20subtype%3Dgml%2F3.2&VERSION=2.0.0&TYPENAMES=su-grid%3AStatisticalGridCell&NAMESPACES=xmlns%28su-grid%2Chttp%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Fsu-grid%2F4.0%29&SERVICE=WFS&STARTINDEX=0

It returns:
```
...   numberMatched="0"   ...
```

But this is not correct. The service does offer data. But maybe this stops the test. I think that the service needs to be corrected to show the correct number. But if the validator would report that no data could be found (or something similar), it might be easier to find out what is going on.

**Comment by josemasensio** [comment] 2019-11-26 13:49
Dear @thijsbrentjens 

Thank you for your collaboration and your messages. Sorry for the delay.

We will appreciate if you could attach your test report. The reload of the staging instance deleted all the test from there. We would like to see the result and the logs from your report.

Thank you and best regards.

**Comment by josemasensio** [comment] 2019-12-04 15:51
Dear @thijsbrentjens,

Thank you for your message. We have been discussing your message and we agreed that we could improve the error message on a future development.

Best regards.

**Comment by thijsbrentjens** [comment] 2020-08-17 08:23
Dear @josemasensio , this issue is still open. Could you give an update maybe? Or could it be scheduled for a release / milestone? Thanks!

**Comment by fabiovinci** [comment] 2022-09-22 08:45
Dear @thijsbrentjens,

we cannot reproduce the error now because the service is no longer available.
We will close the issue, please reopen it or open a new issue if the error persists.

**Closed as completed by fabiovinci** 2022-09-22 08:45 UTC
Labels: enhancement
