### ISSUE TITLE
INSPIRE View Service compliance using Geoserver 2.15

### ISSUE THREAD

**Issue by grigoriouelena** [INSPIRE-MIF/helpdesk-validator#171] opened 2019-12-02 08:07 UTC
I am using GeoServer 2.15 to provide the INSPIRE view service. I am testing it with the INSPIRE reference validator and the test fails for the GetMap operation. The validator expects the service to throw an exception when the parameters, “version”, styles”, “crs” and “transparent” are missing. Unfortunately GeoServer does not throw the exception. Looking at the standard specification, it seems that ¾ of these parameters, except “transparent”, are mandatory. I tried to click the “Strict CITE compliance” check box in the GeoServer WMS settings page, but with no luck.

I know that this is not a validator issue but I would be very interested to hear from other colleagues that use the same application to provide the INSPIRE view service. Are there any suggestions on how I could solve this?

A test service I am checking is: http://geoportal.ypen.gr/geoserver/pf/ows?service=wms&version=1.3.0&request=GetCapabilities

And the corresponding test report is: http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDa69b1f12-9c06-40b2-9b81-25bc38141c00.html

p.s.1: I have already asked a question in StackExchange: https://gis.stackexchange.com/questions/343141/geoserver-wms-inspire-validation/343272#343272

p.s.2: The test also fails for the missing harmonised layer name but I found other issues on this topic so it is not necessary to discuss it here. 

Thank a lot in advance.

Elena

**Comment by danielnavarrogeo** [comment] 2019-12-02 09:07
Dear @grigoriouelena,

Thank you for comment. As you mentioned this is not a validator issue. You might want to open this discussion in the forum:
https://inspire.ec.europa.eu/forum/

Regards

**Comment by grigoriouelena** [comment] 2019-12-03 09:44
Dear danielnavarrogeo,

I already asked in the inspire forum https://inspire.ec.europa.eu/forum/discussion/view/261825/geoserver-wms-does-not-pass-the-inspire-validator-test

but unfortunately I got no replies till today.

**Comment by danielnavarrogeo** [comment] 2019-12-05 16:43
Dear @grigoriouelena 

We are sorry to hear that you did not get any response.

We would like to keep this space strictly for INSPIRE validator issues and to promote the use of the forum for any other related topic with INSPIRE.

We will keep this issue open for a while. But we encourage the users to answer to this topic in the forum.

Regards

**Comment by MarcoMinghini** [comment] 2019-12-05 18:44
Dear @grigoriouelena,
I would also suggest to approach the GeoServer community to find out more about this GeoServer-specific issue.

**Comment by grigoriouelena** [comment] 2019-12-09 08:48
Dear @danielnavarrogeo & @MarcoMinghini ,

Thank you for your comments.

I have already asked in the INSPIRE forum and in StackExchange. I will try other Geoserver channels.

You may remove the issue.

Best,
Elena

**Comment by nmtoken** [comment] 2020-03-09 16:41
You should think the test would also fail on use of **wms** and not **WMS** in the service parameter

**Comment by iuriemaxim** [comment] 2020-10-15 14:28
@grigoriouelena The only solution to the problem is to ask a programmer to adapt the Geoserver source code in order to make it compliant with INSPIRE,

WMS service to test (Geoserver): https://inspire-staging.meteoromania.ro/WIGOS/WMS?service=WMS&request=GetCapabilities
Test results: https://inspire.ec.europa.eu/validator/v2/TestRuns/EID061ed647-938c-4950-b4d1-1642e78b855e.html
![image](https://user-images.githubusercontent.com/20813598/96143339-ad363580-0f0b-11eb-9756-1876cb3a2f2a.png)

**Comment by nmtoken** [comment] 2020-10-16 10:21
You'd think this would also fail the OGC CITE test, it's just the INSPIRE validator that's flagging the issue.

**Comment by iuriemaxim** [comment] 2020-10-16 13:26
> You'd think this would also fail the OGC CITE test, it's just the INSPIRE validator that's flagging the issue.

Not clear exactly what do you mean, but indeed there is no prove that the current version of the Geoserver 2.18 or the 2.15 version (from 2019) mentioned above, will pass the OGC tests for WMS as it is not listed here: https://www.ogc.org/resource/products/byspec/?specid=107. 
Only versions 2.6.1 (tested in 2012) and 2.9.1 (tested in 2016) are mentioned.

The current version of the OGC WMS test is 1.25 https://cite.opengeospatial.org/teamengine/about/wms13/1.3.0/site/
Release notes of the OGC WMS test, to see the changes that were made from 2016 onward can be found here https://cite.opengeospatial.org/teamengine/about/wms13/1.3.0/site/relnotes.html

@grigoriouelena mentioned that ”The validator expects the service to throw an exception when the parameters, “version”, styles”, “crs” and “transparent” are missing.”. And except for transparent these are mandatory by the [WMS standard.](https://www.ogc.org/standards/wms). So if these mandatory parameters are missing from a GetMap request, Geoserver should respond with an exception, indicating that the expected parameters “version”, styles” and/or “crs” are missing.

![image](https://user-images.githubusercontent.com/20813598/96262536-960a4d00-0fca-11eb-96f1-ca7e092257d7.png)

Regarding TRANSPARENT parameter, the problem is not quite correctly indicated by @grigoriouelena as this is an optional parameter. If I remember well, the INSPIRE Validator triggers an error because for a request such as ”TRANSPARENT=YES” or ”TRANSPARENT=ZZZ”, Geoserver is not responding with an exception but is interpreting this as ”TRANSPARENT=FALSE”. This means that Geoserver is not responding with an exception if the value of the TRANSPARENT parameter is another one than the expected TRUE or FALSE and this is also a requirement of the WMS standard.

As these are OGC requirements, most probably tested as well by the OGC, the current version of the Geoserver will not pass the OGC WMS tests. It would be quite odd if the OCG WMS test would not test that a WMS is not responding with an exception when the GetMap request is made without mandatory parameters.

As far as I know, INSPIRE validator is not checking the WMS conformity against the OGC tests, because in order to pass those tests some specific test data should be served by the tested WMS. Therefore the INSPIRE validator has its own WMS tests based on a specific data set that need to be loaded in the database for the OGC testing.

In order to pass either the INSPIRE or OGC tests the source code of Geoserver should be modified. I am not sure if a modified version of Geoserver that is passing the INSPIRE tests will pass also the OGC tests and viceversa, but I know that it is possible to modify the Geoserver code in order to pass the INSPIRE tests, as an example was provided in the previous post.

**Comment by nmtoken** [comment] 2020-10-16 14:26
@iuriemaxim  I agree GeoServer should be fixed.  I was trying to comment that though this issue has been presented as an INSPIRE issue, that the issues are far wider.

_As far as I know, INSPIRE validator is not checking the WMS conformity against the OGC tests, because in order to pass those tests some specific test data should be served by the tested WMS._  Yes, that's my previous experience for a full test but even without the test dataset you still get a good idea about compliance with regards responses to malformed requests.

**Comment by MarcoMinghini** [comment] 2021-03-31 12:26
As this issue is open since a long time and a discussion was already started in the (old) Community Forum, we close it.

However, please note that technical issues which are software-specific (like this one) are not in scope of the INSPIRE helpdesks and in the future shall be discussed outside, e.g. in software-specific mailing lists/channels or in general channels like [GIS Stack Exchange](https://gis.stackexchange.com/).

**Closed as completed by MarcoMinghini** 2021-03-31 12:26 UTC
Labels: discussion
