### ISSUE TITLE
problem with URI 

### ISSUE THREAD

**Issue by sofiaribeiro-apa** [INSPIRE-MIF/helpdesk-validator#520] opened 2021-03-02 16:45 UTC
Hello,
I have a problem accessing 'http://www.opengis.net/def/crs/EPSG/0/4258' that cannot be retrieved.
I receive this message: Every URI must be a HTTP URI in a CRS register that when retrieved with HTTP GET returns a definition of the reference system.
What can I do to solve this accessibility uri ?
Best regards
Sofia Cunha

**Comment by danicgc** [comment] 2021-03-03 07:38
Hi,
I had the same problem yesterday. It seems that now this URL (opengis.net...) redirects to a non-verified HTTPS. Unfortunately, I don't know how (nor who) to solve it.

**Comment by sofiaribeiro-apa** [comment] 2021-03-03 10:25
Thank you very much.
Sofia Cunha

**Comment by carlospzurita** [comment] 2021-03-03 10:32
Dears @danicgc and @sofiaribeiro-apa 

We are checking this issue internally on the production instance of the reference validator to see what is happening internally on a request to this service, and how to solve it.

Kind regards.

**Comment by danicgc** [comment] 2021-03-09 11:15
Hi @carlospzurita,
I think it was with some like this GML (address theme): https://datacloud.ide.cat/geodades/inspire-adreces/inspire-adreces-abella-conca-etrs89-geo.gml
Please let me know if you need more details.
Regards,

**Comment by carlospzurita** [comment] 2021-03-10 17:48
If the issue is not persisting, then we are closing it for now. We will keep an eye open for any other instance of the problem.

**Closed as completed by carlospzurita** 2021-03-10 17:48 UTC

**Comment by sofiaribeiro-apa** [comment] 2021-03-11 09:06
Thank you.
Sofia Cunha
