### ISSUE TITLE
Problem with Datetime / Timezone

### ISSUE THREAD

**Issue by Michael-81** [INSPIRE-MIF/helpdesk-validator#175] opened 2019-12-05 09:58 UTC
For /gmd:date/gco:DateTime

The date values shall be expressed using Gregorian calendar and in accordance with [ISO 8601] with either date precision or date and time precision. For date precision the gmd:CI_Date/gmd:date/gco:Date element, and for date and time precision gmd:CI_Date/gmd:date/gco:DateTime element shall be used.

integrate Datetime with Timezone in Test.

```
<gmd:date>
    <gco:DateTime>2017-09-06T00:00:00.000+02:00</gco:DateTime>
</gmd:date>
```

Only the date is to be used for the test.

But also this form of the Datetime with time zones should be readable and should not lead to an error.

**Comment by danielnavarrogeo** [comment] 2019-12-05 16:45
Dear @Michael-81 
We are analyzing this issue. We will keep you posted.
Regards

**Comment by josemasensio** [comment] 2019-12-09 10:37
Dear @Michael-81,

Please, could you provide us the test where you received this issue? 

Thank you and best regards.

**Comment by alitka** [comment] 2020-01-09 14:47
- [x] description of the steps to reproduce the issue
1. go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp and select "Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records"
2. start the test and upload an externale xml-file
[dataset_DE_temporalReference.zip](https://github.com/inspire-eu-validation/community/files/4040909/dataset_DE_temporalReference.zip)
3. the error message returned for the test "Identification > md common req C.11: Temporal Reference" `The metadata record set has 1 record(s) with errors for this assertion.
XML document 'bkgtest.xml', record '941CDFD1-C53D-4ABE-98FD-1C225BA619F8': The date format shall be in conformity with ISO 8601.`
- [x] used browser and version `Firefox Browser 72.0 (64-Bit)`
- [x] a screenshot illustrating the problem
![grafik](https://user-images.githubusercontent.com/29542183/72076974-c1069880-32f6-11ea-988f-1d32e1659aea.png)
- [x] the Test Report (ideally as an attachment to the issue)
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDde980878-83c0-45ac-b1ba-bc7db66bc489.html
- [x] the name of the Test that failed or better: change the `Level of Detail`
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDde980878-83c0-45ac-b1ba-bc7db66bc489.html#EID607c9b3e-904f-4bb7-a2c2-587ddf6ba111

**Comment by danielnavarrogeo** [comment] 2020-01-14 15:26
Dear @Michael-81 

The issue has been fixed in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) environment. 

Could you please check it and provide us feedback?

Regards

**Comment by alitka** [comment] 2020-01-15 14:28
Dear @danielnavarrogeo, 
I have tested the xml-file again and everything is working properly **for the C.11: Temporal Reference**, but now I get an error for C.12: Max One Date of Creation:
- [x] the Test Report with 
`<gmd:dateType>`
`                <gmd:CI_DateTypeCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="creation"/>`
 `             </gmd:dateType>`
[report_DE_temporalReferenceCreation.zip](https://github.com/inspire-eu-validation/community/files/4065293/report_DE_temporalReferenceCreation.zip)

I only can avoid this error, when I change the codeListValue to "publication", but this couldn't be the solution!
- [x] the Test Report with
`<gmd:dateType>`
`                <gmd:CI_DateTypeCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication"/>`
 `             </gmd:dateType>`
[report_DE_temporalReferencePublication.zip](https://github.com/inspire-eu-validation/community/files/4065304/report_DE_temporalReferencePublication.zip)

If I change the the codeListValue to "revision", I get an error for C.13: Not More than one Date of Last Revision:
- [x] the Test Report with
`<gmd:dateType>`
`                <gmd:CI_DateTypeCode codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="revision"/>`
 `             </gmd:dateType>`
[report_DE_temporalReferenceRevision.zip](https://github.com/inspire-eu-validation/community/files/4065312/report_DE_temporalReferenceRevision.zip)

Could you check C.11 in combination with C.12 and C.13, please?

Thanks & regards.

**Comment by danielnavarrogeo** [comment] 2020-01-21 08:00
Dear @alitka 

Thank you for your comments. Since the original issue has been fixed and your comments are related with other requirements, we will mark this issue as solved.

Would you mind openning a new issue with your last comments?

Regards

**Comment by alitka** [comment] 2020-01-24 14:53
Dear @danielnavarrogeo,
I opened a new issue with my last comments: https://github.com/inspire-eu-validation/community/issues/202
Thanks & regards.

**Closed as completed** 2020-03-18 08:19 UTC
Labels: deployed in reference validator
