### ISSUE TITLE
Staging instance does not accept dataset with error message on size

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#697] opened 2022-01-26 10:24 UTC
I tried to validate a dataset (31 MB, 2 MB zipped) with the staging instance but it is reporting that the file size is too large
![grafik](https://user-images.githubusercontent.com/34163838/151146230-e371caaa-89db-4aaf-be55-afa47c6b7242.png)
I expected to be able to validate files up to 50 MB.

What is the current limit for dataset size on the staging instance?

All the best

Johanna

**Comment by dperezBM** [comment] 2022-01-27 11:16
Dear @JohannaOtt,

Thank you for your message. We are going to analyze the issue, we will come back to you once we have a response.

Best regards

**Comment by dperezBM** [comment] 2022-01-27 13:20
Dear @JohannaOtt,

Is it possible to provide us the example you are trying to upload?

Thanks

**Comment by JohannaOtt** [comment] 2022-01-28 13:39
@dperezBM No, that is confidential data. But you can try with this dataset which has a similar dataset (and should be validated against TN-W. Error message is the same.
[inspireTNW_2.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7958879/inspireTNW_2.zip)

**Comment by jenriquesoriano** [comment] 2022-03-01 13:37
Dear @JohannaOtt  , 

we have re-analysed the global architecture of the Staging instance to provide an answer regarding this behaviour reported in the issue. 
This limit comes from the use of an AWS front end when staging using the API Gateway component.
We have made some adjustments to the implementation of the architecture for the Staging environment and a maximum of 50 MB has been set for the files to be added to the platform.
We have also carried out a series of specific tests and they have worked correctly. 

Can you check that the issue is indeed resolved?

Thank you very much.

Best,

**Comment by JohannaOtt** [comment] 2022-03-01 14:13
@jenriquesoriano I can confirm that I can now upload the dataset I used as an example and get the validator to validate. The issue can be closed from my point of view. I will open a new one in case I run into the issue again.

**Comment by jenriquesoriano** [comment] 2022-03-01 14:23
Dear @JohannaOtt  , 

thanks for your promt confirmation, we close the issue accordingly.

Best regards

**Closed as completed by jenriquesoriano** 2022-03-01 14:23 UTC
Labels: solved, deployment
