### ISSUE TITLE
Soil - SoilHorizon throws System Error when testing FAOHorizonSubordinate

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#643] opened 2021-10-29 23:28 UTC
Hi Validator Team,

Upon testing the SoilHorizon feature type, we are experiencing the following error. 

Conformance class: Application schema, Soil > Code list values > FAOHorizonSubordinate

System error in the Executable Test Suite. Please contact a system administrator. Error information:[err:XPTY0004] Item expected, sequence found: (attribute xlink:href {"http://i.... 
 (628/253)

We're not quite sure if this is an XML issue or is this a validator issue.

I've attached the service XML and the validation report.

Please advise.

Thank you,
Robert

[SO_SoilHorizon_service.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7445372/SO_SoilHorizon_service.zip)

**Comment by dperezBM** [comment] 2021-11-02 13:46
Dear @robblis,

Thank you for your message. This is a problem with a loop on the Test Assertion. We will update the corresponding test and we will come back to you once the issue is fixed on our staging instance. 

Best regards.

**Comment by arantzaetxebarria** [comment] 2021-11-10 10:20
Dear @robblis 

We have done a fix in the ETS to solve this issue, it has been updated on the [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) instance. Could you please test again and verify?

Thanks,

Arantza

**Comment by arantzaetxebarria** [comment] 2022-01-14 12:31
Dear @robblis 

As we are going to make a new release in the coming days, we need to confirm that the fix for your issue in the staging environment is right. Could you please verify? Thanks.

Regards

**Comment by robblis** [comment] 2022-01-14 17:24
Hi @arantzaetxebarria,

We retested our Soil themed service against the staging validator. 

This issue seems to be resolved.

Thanks,
Robert

**Closed as completed** 2022-02-03 09:08 UTC
Labels: deployed in reference validator
