### ISSUE TITLE
API post request https://inspire.ec.europa.eu/validator/v2/TestRuns returns 403 

### ISSUE THREAD

**Issue by cedricdcc** [INSPIRE-MIF/helpdesk-validator#750] opened 2022-05-10 09:34 UTC
Before reporting an issue with the INSPIRE validator deployed at JRC, please check the [list of known limitations](https://github.com/INSPIRE-MIF/helpdesk-validator/wiki/Known-limitations).

Please replace these lines with a brief summary of your issue and the expected
behaviour.

To help us investigate the issue, you may want to include:

- I upload an xml file and tried to make a testrun using the following payload 
    {
    "label": "Test run on 15:00 - 01.01.2017 with Conformance class INSPIRE Profile based on EN ISO 19115 and EN ISO 19119",
    "executableTestSuiteIds": [
        "EIDec7323d5-d8f0-4cfe-b23a-b826df86d58c"
    ],
    "arguments": {
        "files_to_test": ".*",
        "tests_to_execute": ".*"
    },
    "testObject": {
        "id": "b502260f-1054-432e-8cd5-4a61302dfdba"
    }
}
- user agent:  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
- screenshot of problem
![image](https://user-images.githubusercontent.com/30471340/167597532-679aef68-0eb9-4d30-9aa2-b384b44602f6.png)

**Comment by fabiovinci** [comment] 2022-05-13 09:27
Dear @cedricdcc,

could you please provide the resource you are testing in order to reproduce the issue?
Thanks

**Comment by cedricdcc** [comment] 2022-05-16 07:23
Hello @fabiovinci 

I've put the XML file that was used in this [link](https://we.tl/t-Fij5n5Gaey).
The uploading of the resource was not a problem but producing a test where the resource would be checked for  INSPIRE compliance was .

I think the best way to reproduce the issue is to run the test in a cacheless incognito env since the problem for me was a 403 forbidden statement.

**Comment by fabiovinci** [comment] 2022-05-16 08:13
Dear @cedricdcc,

thank you for the file. It seems you are validating your metadata against TG Version 1.3, if yes, please consider that since this version is deprecated we don't guarantee support for the solution of related issues.

I tried to validate your MD against TG Version 2.0 and the result seems ok.
See the report: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDa2b4e0cc-1530-46ab-a9e4-283fc5e6e00c

If you need support to understand the errors please don't hesitate to ask.
You can also have a look at the sample metadata that contains inline comments referring to the TG requirements: https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/examples

**Comment by cedricdcc** [comment] 2022-05-16 10:26
Hey @fabiovinci 

What was the testsuite_id ETF ID of the TG Version 2.0?
Could you send the curl request that you have used to make the report?

This is to make sure that I can reproduce what you have done

Thank you in advance for answering my question

**Comment by fabiovinci** [comment] 2022-05-23 14:38
Dear @cedricdcc,

I did the test through the Validator UI (https://inspire.ec.europa.eu/validator/test-selection/index.html).

From the "Advanced options" menu you can see the related conformance classes used and then retrieve the related EID from the API (https://inspire.ec.europa.eu/validator/v2/ExecutableTestSuites.xml).

If you are doing tests through API, please consider that you need an API key, see [this issue](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/594) for more reference.

**Comment by fabiovinci** [comment] 2023-04-03 14:54
Dear @cedricdcc,

I hope that the support provided has helped you solve the problem.

I will close the issue, please reopen it or open a new issue if the error persists.

**Closed as completed by fabiovinci** 2023-04-03 14:54 UTC
