### ISSUE TITLE
Could not load WFS resource after adding server certificate

### ISSUE THREAD

**Issue by kevin-wilhelm-lgrb** [INSPIRE-MIF/helpdesk-validator#899] opened 2022-12-19 19:30 UTC
Dear INSPIRE Validator Team,

we have again problems with the Validator because we changed the server, which provides our INSPIRE services. 
Issue and error response is the same as the last time, whcih can be find here:
https://github.com/INSPIRE-MIF/helpdesk-validator/issues/686#issue-1101328627

Tested service was:
https://services.lgrb-bw.de/inspire/services/nz_d?REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0

Please install our new server certificates (staging and productive environment) for:
https://services.lgrb-bw.de

Thank you very much for your help.

Best regards
Kevin

**Comment by jenriquesoriano** [comment] 2022-12-21 16:11
Dear @kevin-wilhelm-lgrb ,

we are including your certificate in the production instance.
We will inform you as soon as it is ready.

**Comment by jenriquesoriano** [comment] 2022-12-22 12:14
Dear @kevin-wilhelm-lgrb 
we have incorporated your certificate to the production instance.
Please let us know if it is properly working.

**Comment by kevin-wilhelm-lgrb** [comment] 2022-12-22 16:22
Dear @jenriquesoriano 
thank you very much for including our server certificate.
Unfortunatelly we still get an 500 error when testing in the productive environment. 
JSON response is as following:

error: The test run initialization failed due to an internal error. Please contact a system administrator.
timestamp: 1671725409572
url: http://inspire-validator.eu-west-1.elasticbeanstalk.com:8080/validator/v2/TestRuns
id: l.internal.testrun.initialization.error
{
	"stacktrace": [
		"de.interactive_instruments.exceptions.ObjectWithIdNotFoundException: An object with the id \"ed2d3501-d700-4ff9-b9bf-070dece8ddbd\" could not be found!",
		"\tat de.interactive_instruments.etf.testdriver.EtsLookupSet.getResolved(EtsLookupSet.java:119)",
		"\tat de.interactive_instruments.etf.testdriver.DefaultTestDriverManager.createTestRun(DefaultTestDriverManager.java:177)",
		" [wrapped] de.interactive_instruments.etf.testdriver.TestRunInitializationException: de.interactive_instruments.exceptions.ObjectWithIdNotFoundException: An object with the id \"ed2d3501-d700-4ff9-b9bf-070dece8ddbd\" could not be found!",
		"\tat de.interactive_instruments.etf.testdriver.DefaultTestDriverManager.createTestRun(DefaultTestDriverManager.java:226)",
		"\tat de.interactive_instruments.etf.testdriver.TestDriverManager.createTestRun(TestDriverManager.java:62)",
		"\tat de.interactive_instruments.etf.webapp.controller.TestDriverController.create(TestDriverController.java:149)",
		"\tat de.interactive_instruments.etf.webapp.controller.TestRunController.initAndSubmit(TestRunController.java:248)",
		" [wrapped] de.interactive_instruments.etf.webapp.controller.LocalizableApiError: de.interactive_instruments.etf.testdriver.TestRunInitializationException: de.interactive_instruments.exceptions.ObjectWithIdNotFoundException: An object with the id \"ed2d3501-d700-4ff9-b9bf-070dece8ddbd\" could not be found!",
		"\tat de.interactive_instruments.etf.webapp.controller.TestRunController.initAndSubmit(TestRunController.java:260)",
		"\tat de.interactive_instruments.etf.webapp.controller.TestRunController.start(TestRunController.java:510)",
		"\tat sun.reflect.GeneratedMethodAccessor183.invoke(Unknown Source)",
		"\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
		"\tat java.lang.reflect.Method.invoke(Method.java:497)",
		"\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)",
		"\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)",
		"\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)",
		"\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)",
		"\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)",
		"\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)",
		"\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)",
		" [wrapped] org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is de.interactive_instruments.etf.webapp.controller.LocalizableApiError: de.interactive_instruments.etf.testdriver.TestRunInitializationException: de.interactive_instruments.exceptions.ObjectWithIdNotFoundException: An object with the id \"ed2d3501-d700-4ff9-b9bf-070dece8ddbd\" could not be found!",
		"\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:982)",
		"\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)",
		"\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)",
		"\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)",
		"\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:707)",
		"\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)",
		"\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)",
		"\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)",
		"\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)",
		"\tat de.interactive_instruments.etf.webapp.filter.ApiFilter.doFilterInternal(ApiFilter.java:89)",
		"\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
		"\tat org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)",
		"\tat org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)",
		"\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)",
		"\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)",
		"\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)",
		"\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)",
		"\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)",
		"\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)",
		"\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)",
		"\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)",
		"\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)",
		"\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)",
		"\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)",
		"\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)",
		"\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)",
		"\tat org.eclipse.jetty.server.Server.handle(Server.java:517)",
		"\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)",
		"\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)",
		"\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)",
		"\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)",
		"\tat org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)",
		"\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)",
		"\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)",
		"\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)",
		"\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)",
		"\tat java.lang.Thread.run(Thread.java:745)"
	]
}

**Comment by fabiovinci** [comment] 2023-01-09 10:13
Dear @kevin-wilhelm-lgrb,

we are not able to reproduce the issue since your WFS is no longer accessible, there is a "504 Gateway Time-out" error, could you please check?

**Comment by kevin-wilhelm-lgrb** [comment] 2023-01-11 13:05
Dear @fabiovinci,
sorry for any inconvenience. We had a problem with the specific container on the server. The service is now available.

**Comment by fabiovinci** [comment] 2023-01-11 14:52
No problem, now that the service is back we can investigate the new error.

**Comment by kevin-wilhelm-lgrb** [comment] 2023-01-19 10:24
Dear @fabiovinci,
due to an update of our Kubernetes environment on tuesday Jan 17, 2023 our certificates may have changed again.
Please use the new ones. Thank you very much.

**Comment by fabiovinci** [comment] 2023-02-06 11:09
Dear @kevin-wilhelm-lgrb,

we will add your new certificate.

**Comment by jenriquesoriano** [comment] 2023-02-20 15:42
Dear @kevin-wilhelm-lgrb ,
We have incorporated your certificate.
Please let us know if there is any issue at this regard.

**Comment by fabiovinci** [comment] 2023-04-05 08:34
Dear @kevin-wilhelm-lgrb,

both instances are now able to load your resource.
I will close the issue, please reopen it or open a new issue if the error persists.

**Closed as completed by fabiovinci** 2023-04-05 08:34 UTC
