### ISSUE TITLE
INSPIRE Validator extremely slow

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#884] opened 2022-11-25 06:53 UTC
Dear all,

I know that Monitoring is close so there is more pressure on the INSPIRE Validator, but now it is impossible to work with it. It runs the tests endlessly, does anyone have the same problem and can somebody fix this?

**Comment by jenriquesoriano** [comment] 2022-11-25 07:23
Dear @Ana-SGA 

thank you very much for your feedback and for sharing your impressions of the INSPIRE Reference Validator with the Community.
As you correctly point out, due to the approaching Monitoring & Reporting 2022 process, the INSPIRE Reference Validator is receiving increased usage in the production instance. In this regard, we are carrying out a series of tests and adjustments that will result in an improvement of the perceived performance.
In any case, for validations that might be considered massive or sustained over time, we strongly recommend deploying the [docker release](https://github.com/INSPIRE-MIF/helpdesk-validator/releases) in the organisation or in a local validation environment so as not to saturate the production instance.

We will keep you informed of the progress in this regard.

**Comment by Ana-SGA** [comment] 2022-11-25 10:52
Dear @jenriquesoriano,

thank you. I really hope that you will soon make upgrades that will help the INSPIRE Validator not to be so terribly slow. And please, keep us updated on progress made.

**Comment by dhdeangelis** [comment] 2022-11-27 07:54
> Dear @jenriquesoriano,
> 
> thank you. I really hope that you will soon make upgrades that will help the INSPIRE Validator not to be so terribly slow. And please, keep us updated on progress made.

@Ana-SGA as noted above the problem is that the public instance gets a lot of usage right now and one simple solution is running your own instance using the docker release.

**Comment by Ana-SGA** [comment] 2022-12-05 10:48
Dear all, @jenriquesoriano,

the Validator currenty works for metadata and WMS, but doesn't work for WFS and datasets. I tried to test this weekend, thinking that during the weekend no one will test or that there will be at least just a little less pressure on the Validator, but without success.

**Comment by jenriquesoriano** [comment] 2022-12-05 21:39
Dear @Ana-SGA ,

we have reviewed the test runs on the weekend (Sunday) and we have found a test run that could be (or not) yours according to the provided description (WFS).
This test run has a timeout (20 min) in the OGC Team Engine dependency while the rest of tests in the Validator were executed. It is possible tha this timeout may have led you to think that the test was not working properly (if it was your test).
In any case, could you provide us with the service you want to validate so that we can test it accordingly and verify it?
If you consider so, we can treat it in a separate issue, specific to this topic.

Please see the test:

![imagen](https://user-images.githubusercontent.com/25343632/205746915-2339ff39-923f-4877-bf87-ea6e5b83c2fe.png)

**Comment by Ana-SGA** [comment] 2022-12-06 06:57
Dear @jenriquesoriano,

you're right, it is the Timeout error - I have opened new issue #891 as you suggested.

**Comment by fabiovinci** [comment] 2023-03-17 08:57
Dear @Ana-SGA,

since the problem has been managed in a separate issue, I will close close this one.
Please reopen it or open a new one if the error persists.

**Closed as completed by fabiovinci** 2023-03-17 08:57 UTC
Labels: question
