### ISSUE TITLE
When is ETS going to support and validate the new schema?

### ISSUE THREAD

**Issue by LauraAlemany** [INSPIRE-MIF/helpdesk-validator#30] opened 2019-03-20 09:01 UTC
Hello,

As you can see in the example I attach (xml and document with some images), we have some metadata with the new scheme including <gmx:Anchor>.

[SPAGOBCYLCITDTSLUAPU_NoAnchor_1.zip](https://github.com/inspire-eu-validation/community/files/2987259/SPAGOBCYLCITDTSLUAPU_NoAnchor_1.zip)

When we validate it ininspire-sandbox.jrc.ec.europa.eu/etf-webapp/, there is an error:
![image](https://user-images.githubusercontent.com/33545308/54667951-fafb7980-4aed-11e9-9a48-279e6226ec2b.png)

Do you know when is ETS going to support and validate the new schema?
And when it does, Is it going to support and validate also the old and currrent one version of the schema?

Thank you :)

Laura

**Comment by fabiovin** [comment] 2019-03-20 09:48
Hi Laura,
I made some test with your metadata and the error is due to the different encoding of the element <gmd:dateType>. In the metadata in which you used the gmx:Anchor elements, the element <gmd:dateType> don´t have the value "publication".
The correct encoding is:
 <gmd:dateType>
                              <gmd:CI_DateTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_DateTypeCode"
                                                   codeListValue="publication">publication</gmd:CI_DateTypeCode>
                           </gmd:dateType>

With this encoding the metadata successfully validates.

Best,
Fabio

**Comment by inakidiazdecerio** [comment] 2019-03-20 10:52
Hello @LauraAlemany,

Thanks for reporting the issue. The ETF is validating the new scheme including gmx:Anchor, the problem is due to the test assertion is checking that the attribute codeListValue and text of date type element is "publication". In the example you are providing us there is no text value.

This issue has been already registered (https://github.com/inspire-eu-validation/ets-repository/issues/180) and the solution has been merged into master branch, but is pending to be deployed in reference validator. 

The improvements have been implemented in the staging cloud environment. You can validate your data in the following URL: 

http://etf-staging.eu-west-1.elasticbeanstalk.com/etf-webapp/

We will come back to you when the solution is deployed in production.

Regards.

**Comment by LauraAlemany** [comment] 2019-03-20 10:58
Thank you both :)

@fabiovin , as you said, it validates if I change that.
@inakidiazdecerio , I will follow the registered issue (inspire-eu-validation/ets-repository#180).

Regards.
Laura

**Closed as completed** 2019-11-19 10:49 UTC
Labels: deployed in reference validator
