### ISSUE TITLE
March 2020. Correct changes in the validator?

### ISSUE THREAD

**Issue by mcaletrio** [INSPIRE-MIF/helpdesk-validator#248] opened 2020-03-09 09:43 UTC
Dear colleagues, until last week all our metadata complied with the validation of the INSPIRE validator. Today when I try to validate dataset metadatas that it were valid,  it appears an error related to conformance class. Metadata for interoperability-- character encoding and spatial representation type.

I would like to know if this is due to an error produced because of changes in your codes or if  it’s a new requirement of the validator. Thank you. 

I attach the link to the report: 
http://inspire.ec.europa.eu/validator/v2/TestRuns/EID5798e5c0-c620-4472-b6c3-55fed55371d4.html?lang=es

**Comment by iuriemaxim** [comment] 2020-03-09 11:53
Hi,

It is due to a change made by ISO, see issues: https://github.com/inspire-eu-validation/community/issues/246, https://github.com/inspire-eu-validation/community/issues/245

Iurie

**Comment by danielnavarrogeo** [comment] 2020-03-09 14:27
Dear @mcaletrio and @iuriemaxim 

This is indeed caused by ISO schemas which were moved to a different location as @iuriemaxim has mentioned. We are analyzing the best approach to manage this.

We would like to remind that the transition period from Metadata 1.3 to Metadata 2.0 has ended already. Therefore, only Metadata 2.0 is nowadays valid.

Regards

**Comment by iuriemaxim** [comment] 2020-03-09 16:01
Dear @danielnavarrogeo 

This is correct that the transition period from Metadata 1.3 to Metadata 2.0 has ended already. Can you please confirm that the EC Geoportal (https://inspire-geoportal.ec.europa.eu/) is able to harvest metadata files made according to version 2.0 of the TG? Our national representative informed us that the EC validator is able to harvest only metadata made according to version 1.3 of the TG.

Regards,

**Comment by mcaletrio** [comment] 2020-03-11 14:35
Dear colleagues, it's right that the transition period from Metadata 1.3 to Metadata 2.0 has ended already. We are going to make the changes, but meanwhile  it could be very useful to have a dataset metadata and service metadata that validate with the validator new version.
Could you be so kind to share with us a dataset metadata and service metadata good practice to speed up the transition?
Thank you.

Best regards.

**Comment by danielnavarrogeo** [comment] 2020-03-11 15:00
Dear @mcaletrio 

You find a metadata for dataset here:
https://github.com/inspire-eu-validation/community/blob/master/examples/Dataset_metadata_2.0_example

And a metadata for services here:
https://github.com/inspire-eu-validation/community/blob/master/examples/NetworkService_WMS_metadata_2.0_example

Regards

**Comment by mcaletrio** [comment] 2020-03-11 15:21
Perfect! Thank you very much. 
Best regards

**Comment by iuriemaxim** [comment] 2020-03-11 15:40
@danielnavarrogeo can you please confirm that the EC Geoportal is able to harvest metadata made according to version 2.0 of the Metadata TG?
We already have all metadata in version 2.0 but the national representative informed us the the EC Geoportal currently support only version 1.3 metadata files and ask us to revert to the old versions.

**Comment by iuriemaxim** [comment] 2020-03-11 15:49
Dear @MarcoMinghini can you please confirm if the EC validator is able to harvest metadata made according to version 2.0 of the Metadata TG?

We are rounding in circles, with no solution: Metadata 1.3 cant be now validated with the ETF and Metadata 2.0 cant be harvested by the EC Geoportal.

**Comment by danielnavarrogeo** [comment] 2020-03-11 15:51
Dear @iuriemaxim 

We are waiting for confirmation.

Regards

**Comment by mcaletrio** [comment] 2020-03-11 16:01
Thank you for the url examples.
The validator when It validate the dataset metadata it doen't report that the test have been made. 
url of the report: http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDf530199a-cdf5-4f0e-b9ba-6caeaf99c198.html?lang=es 
Is that correct or is it because of the transition?

The service metadata example has validation errors. 

Thank you

**Comment by mcaletrio** [comment] 2020-03-11 16:03
Thank you for the url examples.
The validator when It validates the dataset metadata it doesn't report that the tests have been made.
url of the report: http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDf530199a-cdf5-4f0e-b9ba-6caeaf99c198.html?lang=es
Is that correct or is it because of the transition?
The service metadata example, has validation errors. Thank you

**Comment by MarcoMinghini** [comment] 2020-03-11 16:14
Dear @mcaletrio,
I have just run the validation for the 2 metadata mentioned by @danielnavarrogeo and both pass the validation. Please note that a difference compared to MD TG 1.3 is that now the Conformance Classes you have to select are different between datasets and services, so this might be the reason of your failed tests.

Together with the examples, I suggest you to look at the MD TG 2.0 to understand the meaning of the several Conformance Classes.

**Comment by MarcoMinghini** [comment] 2020-03-11 16:41
Dear @iuriemaxim, @mcaletrio, all,
I propose to close this issue since it is a duplicate of #245 and to continue the discussion there.

To answer your questions:

> Dear @MarcoMinghini can you please confirm if the EC validator is able to harvest metadata made according to version 2.0 of the Metadata TG?

I guess you refer to the [INSPIRE Geoportal](https://inspire-geoportal.ec.europa.eu/). We are working to increase the support of the INSPIRE Geoportal for MD TG 2.0. Full support will be provided during the year, but MD compiled according to TG 2.0 can and should be already used to facilitate the transition. To help us reach full support, you can report any issue you may experience in the [Geoportal helpdesk](https://ies-svn.jrc.ec.europa.eu/projects/geoportal/).

> We are rounding in circles, with no solution: Metadata 1.3 cant be now validated with the ETF and Metadata 2.0 cant be harvested by the EC Geoportal.

The second part of the question is answered above, the first part is answered by [my last comment](https://github.com/inspire-eu-validation/community/issues/245#issuecomment-597733156) in #245.

**Comment by mcaletrio** [comment] 2020-03-12 08:34
Dear colleagues. Thank you for the support. We will be attentive to evolution.
Best regards

**Comment by danielnavarrogeo** [comment] 2020-04-07 14:00
Dear all,

We will close this issue since a duplicated issue already exists (#245).

Regards

**Closed as completed by danielnavarrogeo** 2020-04-07 14:00 UTC
Labels: duplicate

**Comment by iuriemaxim** [comment] 2020-04-08 07:05
Issue #245 is not the same with this one (#248). Currently the EC Geoportal is not able to harvest Metadata files made according to version 2.0.
