### ISSUE TITLE
truncated HTML output of the test result

### ISSUE THREAD

**Issue by Alexander-Barth** [INSPIRE-MIF/helpdesk-validator#232] opened 2020-03-03 09:17 UTC
I try to validate a viewing service but the last test report is truncated. The HTML result stops with `supportedLanguages &lt;&l` at the test 47 (and not with `...</html>`). I would like to have additional information why the test at47-getcapabilities-layer-style-legend-url fails, in particular the full test code. Any subsequent tests are not available in the test report.

To help us investigate the issue, you may want to include:

- [x] a description of the steps to reproduce your issue

* go to http://inspire.ec.europa.eu/validator/#start-tests
* accept cookies
* choose WMS
* start test
* insert the address: https://ec.oceanbrowser.net/test-1/Python/web/wms?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0

- [x] the browser and version used

Firefox 70.0.1 and google-chrome (80.0.3987.122-1)

- [x] a screenshot illustrating the problem

The HTML code ends with:

```html
                           </table><br><div class="DoNotShowInSimpleView">
                              <div class="ExecutionStatement"><label for="d73884e1963"></label><textarea id="d73884e1963.executionStatement" data-mini="true" readonly class="ui-input-text ui-shadow-inset ui-body-inherit ui-corner-all ui-mini ui-textinput-autogrow">import de.interactive_instruments.etf.suim.TranslatableAssertionError;
def tc = testRunner.testCase.testSuite.project.testSuites["GetCapabilities_Operation"].testCases["initial-testcase"];
def response = tc.getTestStepByName("http-request").getPropertyValue("Response");
def capabilities = new XmlSlurper(false, true).parseText(response);

testRunner.testCase.setPropertyValue('language', '');
testRunner.testCase.setPropertyValue('legendEndpoint', '');
def defaultLanguage = capabilities.Capability.ExtendedCapabilities.SupportedLanguages.DefaultLanguage.Language.toString();
def supportedLanguages = [];
supportedLanguages &lt;&lt; capabilities.Capability.ExtendedCapabilities.SupportedLanguages.DefaultLanguage.Language;
for (x in capabilities.Capability.ExtendedCapabilities.SupportedLanguages.SupportedLanguage){
	supportedLanguages &lt;&lt; x.Language;
}

def tsGetCapabilities = testRunner.testCase.testSuite.project.testSuites["GetCapabilities_Operation"].testCases["at47-getcapabilities-layer-style-legend-url"].getTestStepByName('http-getcapabilities-specific-language');
def tsGetLegend = testRunner.testCase.testSuite.project.testSuites["GetCapabilities_Operation"].testCases["at47-getcapabilities-layer-style-legend-url"].getTestStepByName('http-getlegend');

for (x in supportedLanguages){
	testRunner.testCase.setPropertyValue('language', x.toString());
	tsGetCapabilities.setDisabled(false);
	tsGetCapabilities.run(testRunner, context);
	capabilitiesLanguaged = new XmlSlurper(false, true).
```
- [x] the Test Report (ideally as an attachment to the issue)

http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDe11afac4-a751-45a1-bb62-9d8a21bf6663.html

Also attached:

[EIDe11afac4-a751-45a1-bb62-9d8a21bf6663.html.txt](https://github.com/inspire-eu-validation/community/files/4280265/EIDe11afac4-a751-45a1-bb62-9d8a21bf6663.html.txt)

- [x] the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`

at47-getcapabilities-layer-style-legend-url

- [x] the URL of your service / the file you have uploaded or referenced (as
an attachment).

https://ec.oceanbrowser.net/test-1/Python/web/wms?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0

If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be investigated for services/datasets that we cannot
access.

**Comment by danielnavarrogeo** [comment] 2020-03-09 15:10
Dear @Alexander-Barth 

We are analyzing this issue. It seems to be related to the legends requests.

We will come back to you with our findings.

Regards

**Comment by Alexander-Barth** [comment] 2020-03-10 10:11
Thanks a lot for the update!

**Comment by danielnavarrogeo** [comment] 2020-03-10 12:26
Dear @Alexander-Barth 

There are many links to legends of the layers that do not work (Layer/Style/LegendURL/OnlineResource).

For instance, this URL does not work: 

https://ec.oceanbrowser.net/test-1/Python/web/wms?request=GetLegendGraphic;width=100;layer=Water_body_ammonium.combined.nc%252AWater_body_ammonium_L2;format=image/png;style=pcolor_flat;height=300

Regards

**Comment by Alexander-Barth** [comment] 2020-03-18 08:18
Dear @danielnavarrogeo
Thank you for looking into this issue. I have corrected the legend URL and now I get a full HTML report.

As it is likely that the validator will get tested on not yet valid WMS services, it would still be good to report a full report (including the errors), don't you think?

Thanks again,
Alexander

**Comment by carlospzurita** [comment] 2020-07-03 09:17
Dear @Alexander-Barth 
We are closing this issue as the problem is no longer reproducible. We will keep as a reference for future problems with WMS requests that may cause any problem in the validator.

Thank you

**Closed as completed by carlospzurita** 2020-07-03 09:17 UTC
