### ISSUE TITLE
linkages checker tool for download wcs service

### ISSUE THREAD

**Issue by stopa3** [INSPIRE-MIF/helpdesk-validator#671] opened 2021-12-07 13:08 UTC
Dear all,

We are trying  to emulate the [checks between metadatada (dataset) and metadata (download wcs service)](https://inspire-geoportal.ec.europa.eu/linkagechecker.html). 
According [Geoportal workflow for establishing links between data sets and network services](https://inspire-geoportal.ec.europa.eu/files/INSPIRE_Geoportal_process_for_data-service_linking_v1.0.pdf) it looks wcs download service is not supported to check linkage.

Am I right?

Many thanks,

Martin Koska
Slovakia

**Comment by fabiovin** [comment] 2021-12-07 15:36
Dear @stopa3,

see the related reply in this issue https://github.com/INSPIRE-MIF/helpdesk-geoportal/issues/12.

It seems the issue is related to geoportal and not to the validator, so I'm closing it.
Please reopen it or open a new one if you have a problem with the validator.

Thanks,
Fabio

**Closed as completed by fabiovin** 2021-12-07 15:36 UTC
