### ISSUE TITLE
Strange response on validating WFS-service (redirection issue ? )

### ISSUE THREAD

**Issue by MichaelOstling** [INSPIRE-MIF/helpdesk-validator#156] opened 2019-11-15 14:52 UTC
**When validating the WFS-Service**
https://opendata-view.smhi.se/svar2012_coast-sea/wfs?service=wfs&request=getcapabilities

**That is documented in the record**
https://www.geodata.se/geodataportalen/srv/swe/csw-inspire-swe?request=GetRecordById&service=CSW&version=2.0.2&id=c9940808-9276-4bfb-a717-bf6d2cbb7325&elementSetName=full&outputSchema=http://www.isotc211.org/2005/gmd

**We get some strange results in validation-report** 
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID52bcab05-24d7-4e12-abc1-227fea13419b.html

(The default ETF-validator have not been working for 3 days so I use the staging version)

I see in the validator-results that it contain many errors related to missing html-tags (hr) in the response

`OGC TEAM Engine reported a failed test: org.xml.sax.SAXParseException; lineNumber: 13; columnNumber: 5; The element type hr must be terminated by the matching end-tag "hr".`

It seems that there could be some redirection issues again.

I think the WFS-service is behind some kind of cache/proxy (Varnish)

Can it be that there are redirects done that validator do not handle?

When inspecting the capabilities response in browser I see no problems

Kind Regards 
Michael Östling

**Comment by josemasensio** [comment] 2019-11-18 07:25
Dear @MichaelOstling,

Thank you for your message. We will check what is going on to fix as soon as possible. 
Thanks for your feedback.

Best regards.

**Comment by danielnavarrogeo** [comment] 2019-12-03 11:02
Dear @MichaelOstling 
We think the issue you reported was related with some deployments problems we had. The test now seems to run properly.
Could please check it again and tell us if the issue is solved?
Regards

**Comment by danielnavarrogeo** [comment] 2020-01-13 16:30
Dear @MichaelOstling 

We will close the issue since the described issue does not appear anymore in the current deployment.

Thank you for your participation and please feel free to open any new issue you find related with the INSPIRE validator.

Regards

**Closed as completed** 2020-01-13 16:30 UTC
