### ISSUE TITLE
System error in the Executable Test Suite. Please contact a system administrator. Error information: [err:FODC0002]

### ISSUE THREAD

**Issue by christian-schigl** [INSPIRE-MIF/helpdesk-validator#247] opened 2020-03-09 08:28 UTC
Hello,

last week I had to notice that some of the XML-Ressourcedocuments referenced in my INSPIRE - Metadata XMLS were no longer valid :
**http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/Codelist/ML_gmxCodelists.xml**
hat obviously moved to
**https://standards.iso.org/iso/19139/resources/ML_gmxCodelists.xml**
I replaced that in my XMLs and on repeating the tests via the ETF Validator i got a "Failed" status on the "Character Encoding" and "Spatial Representation Type" Tests, stating the following 

Error Message:

System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:FODC0002] Resource "https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml" not found.

Since the mentioned link "https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml" does not appear in my XML-files i presume that it is used within your testsuite ...

- [ ] a description of the steps to reproduce your issue
-> ETF Validator, Metadata 1.3
- [ ] the browser and version used
-> Firefox 68.2.0esr
- [ ] a screenshot illustrating the problem
-> see the attached report
- [ ] the Test Report (ideally as an attachment to the issue)
-> attached
- [ ] the name of the Test that faile

d or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`
-> "SIS_10_review"
- [ ] the URL of your service / the file you have uploaded or referenced (as
an attachment).
-> Uploaded File: 10_SchutzgebieteLandesgesetzgebungMerge.xml
[SIS_10_review.zip](https://github.com/inspire-eu-validation/community/files/4305453/SIS_10_review.zip)

If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be investigated for services/datasets that we cannot
access.

**Comment by iuriemaxim** [comment] 2020-03-09 12:00
Is the same with issue https://github.com/inspire-eu-validation/community/issues/245 due to issue https://github.com/inspire-eu-validation/community/issues/246

**Comment by danielnavarrogeo** [comment] 2020-03-09 14:27
Dear @christian-schigl and @iuriemaxim 

This is indeed caused by ISO schemas which were moved to a different location as @iuriemaxim has mentioned. We are analyzing the best approach to manage this.

We would like to remind that the transition period from Metadata 1.3 to Metadata 2.0 has ended already. Therefore, only Metadata 2.0 is nowadays valid.

Regards

**Comment by MarcoMinghini** [comment] 2020-03-11 16:28
I will close this issue and invite you to follow the discussion in #245.

**Closed as completed by MarcoMinghini** 2020-03-11 16:28 UTC
