### ISSUE TITLE
Dataset GML validation - An error has occured uploading file (Code: 0 - ).

### ISSUE THREAD

**Issue by MaiteZabaltza** [INSPIRE-MIF/helpdesk-validator#676] opened 2021-12-13 07:27 UTC
Good Morning,
I have been trying to validate Dataset GMLs for different INSPIRE Themes, such as AM, EF, SO and HY, for the last 2 weeks and every time I uploaded a zip folder with size <50MB, the INSPIRE validator returned an error saying: 
**An error has occurred uploading file (Code: 0 - )**.
Last time I was able to run a test was 25th November 2021. Since then, I have tried several times using different computers as well as, both Google Chrome and Microsoft Edge and I have never succeed. In order to configure my test I checked the Data set box, selected the corresponding INSPIRE annex and theme and I left every conformance class test ticked so all of them were assessed.
Is there any issue with the validator? Or am I doing something wrong?
Do you expect to have it back running soon?
Thank you very much in advance.
Kind regards,
Maite

**Comment by JohannaOtt** [comment] 2021-12-13 07:29
@MaiteZabaltza Is addressed in https://github.com/INSPIRE-MIF/helpdesk-validator/issues/668 AFAIK

**Comment by MaiteZabaltza** [comment] 2021-12-13 08:08
Hi @JohannaOtt,
Thanks for the information. I cleared the cache and launched a new incognito window and I still got the same error when uploading a file of 1.2 MB. Will you update the #668 AFAIK when solved? Or shall we keep trying if we can proceed with the test from time to time?
I'm new in the chat, thanks for helping.
Maite

**Comment by JohannaOtt** [comment] 2021-12-13 08:20
> Will you update the #668 AFAIK when solved?

I just wanted to let you know that the issue is already addressed. I assume the validator team will update it, but I am only a user as well ;)

**Comment by MaiteZabaltza** [comment] 2021-12-13 08:28
Cool! Thanks again, then! :)

**Comment by jenriquesoriano** [comment] 2022-01-01 11:11
Dear @MaiteZabaltza , @JohannaOtt , 

thanks for your contribution and feedback.

As the issue seems to be related with #668 (ready for testing), it should be already solved.

@MaiteZabaltza , we kindly ask you to test it again and provide us with feedback whether the test is successfull or not. 

In case it is not successful, if possible, we kindly ask you to provide us with more detailed information in order to reproduce the reported issue. 
In case it may help, please find a link on how to [report a problem](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/new?template=problem.md), so we may have enough information to check and solve it.

Kind regards,

**Comment by jenriquesoriano** [comment] 2022-01-18 07:51
Dear @MaiteZabaltza , @JohannaOtt 

as issues with regard to the upload of files, have been addressed in #668 , #677 and newly tested , we close this issue accordingly.
![imagen](https://user-images.githubusercontent.com/25343632/149893504-92fc88c2-0a8b-4744-954f-ae37e0375275.png)

In case this issue raises again, we kindly ask you to create a new issue reporting the problem encountered.

We take the chance to thank you again for your contribution and feedback.

Kind regards,

**Comment by arantzaetxebarria** [comment] 2022-01-19 07:46
Dear @MaiteZabaltza 
we close this issue as the validator is working normally.
Please feel free to open a new issue in case you detect any problem.

Regards

**Closed as completed** 2022-01-19 07:45 UTC
Labels: validator down
