### ISSUE TITLE
Cannot open or download WFS service report 

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#693] opened 2022-01-24 11:30 UTC
Dear all,
it seems I can't open or save download service report (WFS). Clicking on "See report" opens the page, but without report - it opens partially and then stops (picture attached). When trying to download the report, I get error "Endpoint request timed out". 
![WFS_report](https://user-images.githubusercontent.com/77394573/150774814-2561791c-4507-4e78-bb0b-2abf8579652c.PNG)
.

**Comment by jenriquesoriano** [comment] 2022-01-24 12:32
Dear @Ana-SGA 

thanks for your feedback and bringing this issue to our attention.
We have run a download WFS service test in order to try to reproduce the reported issue.
We have been able to obtain the test report and also to download it.
![imagen](https://user-images.githubusercontent.com/25343632/150783424-171a06bd-343a-497a-8bb1-f8695a52cfbe.png)



Please see:

- Test report: https://inspire.ec.europa.eu/validator/test-reports/details.html?id=EIDf91d5a8e-c11b-48da-bc6e-ee5b24f2e8aa
- Download test report: https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EIDf91d5a8e-c11b-48da-bc6e-ee5b24f2e8aa.html?download=true

Could you provide us with more details of the input data so we can reproduce the reported issue?

Thanks a lot.

Best,

**Comment by Ana-SGA** [comment] 2022-01-24 13:15
Dear @jenriquesoriano ,

yes, I can open the reports you attached. Here is the WFS service https://nipp.hzinfra.hr/geoserver/tn-ra/wfs?service=WFS&request=GetCapabilities&version=2.0.0 for which I can't open test report (tested for Direct WFS). Thanks for helping.

**Comment by jenriquesoriano** [comment] 2022-02-01 14:22
Dear @Ana-SGA ,

we have launched the test both in production and staging instances.
The execution has been successful and the report and the download of the report can be accessed.

PRODUCTION
https://inspire.ec.europa.eu/validator/test-reports/details.html?id=EID3083733e-dbd4-4cb0-b266-3b124be1fbff
https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EID3083733e-dbd4-4cb0-b266-3b124be1fbff.html?download=true 

STAGING
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-reports/details.html?id=EIDe12057f4-fd9e-4da7-9154-bb1e586b6461
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/TestRuns/EIDe12057f4-fd9e-4da7-9154-bb1e586b6461.html?download=true

Please note that the downloaded reports are quite big and also under heavy-load conditions may lead to a timeout processing the request.

Best regards,

**Comment by Ana-SGA** [comment] 2022-02-02 11:39
Dear @jenriquesoriano ,

now I can open the report. Tried testing and OGC test for WFS 2.0 fails with "OGC TEAM Engine is taking too long to respond. Timeout after 20min.". Why is the Direct WFS test running so long?  That was also a problem before and it seems that this test now lasts even longer (ie compared to WMS test). 

How come your test report has different order of executed tests (pictures attached)?

And, can anyone adjust the ratio between the window of report and footer? Seem that footer is taking too much space, which is uncomfortable when using Validator frequently.

![Executed_tests_order](https://user-images.githubusercontent.com/77394573/152146808-61563f5d-48ba-43a0-b592-953e4857a255.PNG)
.

**Comment by fabiovinci** [comment] 2022-02-16 17:31
Dear @Ana-SGA,

I tried to validate your WFS and the [results ](https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID1683961e-147d-4e36-ae37-22e778efb151) seem ok, the OGC test for WFS 2.0 is executed in a short time.

Could you please try again?

Regarding the footer, unfortunately, we were not able to reduce it because it depends on the layout of the Commission.

**Comment by Ana-SGA** [comment] 2022-02-17 10:32
Dear @fabiovinci ,

hm, did you test this service https://nipp.hzinfra.hr/geoserver/tn-ra/wfs?service=WFS&request=GetCapabilities&version=2.0.0?

I tried a few minutes ago and it failed again with internal server error - https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDee01954d-11de-4729-92eb-de6785d9a5dc? And I tried again now, but now I can't start the test with "an error has occurred"?

The first time I run the test, it was performed significantly faster and that's great :).

**Comment by fabiovinci** [comment] 2022-02-17 15:52
Dear @Ana-SGA,

I confirm I used the service you mentioned.

You are right, sometimes it is not possible to upload the resource, we will investigate further and let you know.

**Comment by jenriquesoriano** [comment] 2022-05-19 10:40
Dear @Ana-SGA ,

we have noticed your web certificate recently changed.
We have updated it in staging accordingly.
Nevertheless the test cannot be completed due to the WFS request is not reachable, receiving an empty response.
Could you kindly double-check the current status of the service?

Thank you in advance.

Best regards,

**Comment by Ana-SGA** [comment] 2022-05-19 10:46
Dear @jenriquesoriano ,

thanks for the information, I'll inform the contractor. 

Kind regards,
Ana

**Comment by fabiovinci** [comment] 2023-03-21 17:17
Dear @Ana-SGA,
since there was no reply from your side, I will close the issue.
Please reopen it or open a new issue if the error persists.

**Closed as completed by fabiovinci** 2023-03-21 17:17 UTC
Labels: question
