### ISSUE TITLE
Land use: Test with Remote file fails with initial error

### ISSUE THREAD

**Issue by g-weber** [INSPIRE-MIF/helpdesk-validator#591] opened 2021-07-20 08:15 UTC
Using remote file the testrun with data set "Land Use" fails initially:
![image](https://user-images.githubusercontent.com/63788779/126284586-cbf512c9-c18e-4e9f-a706-b3490e9594bb.png)

Used url: https://rudolstadt.gajamatrix.de/geoserver/plu_rudolstadt/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&typeName=plu_rudolstadt:SpatialPlan&outputformat=application/gml%2Bxml;+version=3.2.

Using the test with the uploaded xml file provided by the url the test runs without any problem.

**Comment by fabiovin** [comment] 2021-07-28 08:13
Dear @g-weber,

it seems the link provided is not working because the feature type is "_plu_rudolstadt:LU.SpatialPlan_" instead of "_plu_rudolstadt:SpatialPlan_".

In any case, trying with the following link "https://rudolstadt.gajamatrix.de/geoserver/plu_rudolstadt/wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&typeName=plu_rudolstadt:LU.SpatialPlan&outputformat=application/gml%2Bxml;+version=3.2" the test doesn't start.

We will investigate it and we’ll let you know when the solution is available.

**Comment by fabiovinci** [comment] 2022-06-27 09:51
Dear @g-weber,

now it works.

See the validation report: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDbc7d702e-955e-4d66-b598-ea4760ebc32a

Could you please check and confirm that the issue is solved? Thanks

**Comment by fabiovinci** [comment] 2022-09-22 09:42
Dear @g-weber,

I'm closing the issue, please reopen it or open a new one if the problem persists.

**Closed as completed by fabiovinci** 2022-09-22 09:42 UTC
Labels: ready for testing
