### ISSUE TITLE
Validator test NOT Working

### ISSUE THREAD

**Issue by luciatilio** [INSPIRE-MIF/helpdesk-validator#667] opened 2021-11-26 15:42 UTC
- After upoad xml with success, an error occurs.
- Google Chrome Version 96.0.4664.45 (Official Build) (64-bit)
- In attached a print of problem, with also error in developer tools console.
- The test I attempt to execute is for Metadata, Version 2.0, Data sets and data set series
![Untitled](https://user-images.githubusercontent.com/56029826/143604622-356173ad-8bd7-47d5-9113-45892a7941b8.png)

**Comment by MarcoMinghini** [comment] 2021-11-27 11:00
Dear @luciatilio,
I was just able to successfully run the same test. Please let us know if the problem is solved.

**Comment by luciatilio** [comment] 2021-11-28 06:21
So, @MarcoMinghini, just now, I have the same error, but the same xml is correctly processed by staging instance.

**Comment by Ana-SGA** [comment] 2021-11-29 06:55
Dear all,

since last week we also have a problem with the INSPIRE Validator, currently it doesn't even load properly and no test can be run

**Comment by Dnoack49** [comment] 2021-11-29 10:56
Dear all,
in addition to the described problem, we are also not able to access the Test Reports from https://inspire.ec.europa.eu/validator/test-reports/index.html 

It keeps loading:
![grafik](https://user-images.githubusercontent.com/8046960/143855342-22903780-b8f1-4f90-b026-f9251e30f8ee.png)

May it be related to this as well?

**Comment by carlospzurita** [comment] 2021-11-29 11:02
Dear all

We have been working on reproducing the errors accessing the functionality to no avail. One question that remains here and can shed some light on this issue is: how are you accessing the Validator interface? The change on the API gateway access announced [here](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/594#issuecomment-979195084) also implied a modification on the UI to point to this gateway instead of the old link.

Can you try to access to the validator in private mode on your browsers? In order to eliminate any cached content that might remain in your computers.

**Comment by luciatilio** [comment] 2021-11-29 11:14
Ok, in private mode it works.

**Comment by luciatilio** [comment] 2021-11-29 11:18
> t

It works also after a cache emtpying ;)

**Comment by Ana-SGA** [comment] 2021-11-29 11:19
Same here, clearing cache helped

**Comment by carlospzurita** [comment] 2021-11-29 11:27
Great to hear that we have an explanation for this issue! We will also add an update on the announcement to prevent users from running into this problem by clearing the browser caches.

We are closing this issue as it has been tested and approved.

**Closed as completed by carlospzurita** 2021-11-29 11:27 UTC
Labels: validator down

**Comment by Ana-SGA** [comment] 2021-11-29 11:50
@carlospzurita but it seems that we can't test datasets? Validator says "Error code 0-" (tried in private window also)?

**Comment by carlospzurita** [comment] 2021-11-29 12:08
Dear @Ana-SGA 

Please, could you open a separated issue, sharing the Test Suites and an example dataset that you are uploading?

Thank you.
