### ISSUE TITLE
Stuck test when running Protected Sites tests

### ISSUE THREAD

**Issue by hwbllmnn** [INSPIRE-MIF/helpdesk-validator#699] opened 2022-01-26 14:34 UTC
I get occasional stuck tests when testing data sets with the protected sites test class. After a while, the test log just doesn't show any progress any more (for this we're also running the tests with the REST API). The test runs show up in the UI after creating them, and we can also access the log. At some point, the log isn't being updated any more (even after hours).

Example log:

```
26.01.2022 09:49:27 - Preparing Test Run ETF-client c722d190-f7ae-4086-8d5d-b05cd6ee1895 run 1 (initiated Wed Jan 26 09:49:27 UTC 2022)
26.01.2022 09:49:27 - Resolving Executable Test Suite dependencies
26.01.2022 09:49:27 - Preparing 10 Test Task:
26.01.2022 09:49:27 -  TestTask 1 (bb6c2425-848b-4ae9-897e-89533584b99d)
26.01.2022 09:49:27 -  will perform tests on Test Object 'pre17825481996620656117.xml' by using Executable Test Suite 'LAZY.545f9e49-009b-4114-9333-7ca26413b5d4'
26.01.2022 09:49:27 -  with parameters: 
26.01.2022 09:49:27 - etf.testcases = *
26.01.2022 09:49:27 -  TestTask 2 (3386627b-93f7-4ffb-8a15-b04e5d641176)
26.01.2022 09:49:27 -  will perform tests on Test Object 'pre17825481996620656117.xml' by using Executable Test Suite 'Conformance class: Data consistency, General requirements (EID: 61070ae8-13cb-4303-a340-72c8b877b00a, V: 0.2.1 )'
26.01.2022 09:49:27 -  with parameters: 
26.01.2022 09:49:27 - etf.testcases = *
26.01.2022 09:49:27 -  TestTask 3 (458a633b-b2e0-4375-aff2-819315ef9ac5)
26.01.2022 09:49:27 -  will perform tests on Test Object 'pre17825481996620656117.xml' by using Executable Test Suite 'Conformance class: Reference systems, General requirements (EID: 63f586f0-080c-493b-8ca2-9919427440cc, V: 0.2.1 )'
26.01.2022 09:49:27 -  with parameters: 
26.01.2022 09:49:27 - etf.testcases = *
26.01.2022 09:49:27 -  TestTask 4 (00773c68-8a89-43cb-b13b-63ed33b46588)
26.01.2022 09:49:27 -  will perform tests on Test Object 'pre17825481996620656117.xml' by using Executable Test Suite 'LAZY.499937ea-0590-42d2-bd7a-1cafff35ecdb'
26.01.2022 09:49:27 -  with parameters: 
26.01.2022 09:49:27 - etf.testcases = *
26.01.2022 09:49:27 -  TestTask 5 (93df47a5-6154-400a-b511-b88d13df9e67)
26.01.2022 09:49:27 -  will perform tests on Test Object 'pre17825481996620656117.xml' by using Executable Test Suite 'Conformance class: Information accessibility, Protected Sites (EID: b529e8fa-b9f8-4758-acea-1d2af744599f, V: 0.2.3 )'
26.01.2022 09:49:27 -  with parameters: 
26.01.2022 09:49:27 - etf.testcases = *
26.01.2022 09:49:27 -  TestTask 6 (439778e0-0fbf-43d6-91c9-6b42e0a4a342)
26.01.2022 09:49:27 -  will perform tests on Test Object 'pre17825481996620656117.xml' by using Executable Test Suite 'Conformance class: INSPIRE GML application schemas, General requirements (EID: 09820daf-62b2-4fa3-a95f-56a0d2b7c4d8, V: 0.2.7 )'
26.01.2022 09:49:27 -  with parameters: 
26.01.2022 09:49:27 - etf.testcases = *
26.01.2022 09:49:27 -  TestTask 7 (188ca1cf-ad3e-4dff-979d-49f7f127bf63)
26.01.2022 09:49:27 -  will perform tests on Test Object 'pre17825481996620656117.xml' by using Executable Test Suite 'Conformance class: Reference systems, Protected Sites (EID: 828410c1-53f2-4683-bded-481ad9d4d3e9, V: 0.2.0 )'
26.01.2022 09:49:27 -  with parameters: 
26.01.2022 09:49:27 - etf.testcases = *
26.01.2022 09:49:27 -  TestTask 8 (604b00f2-45e7-459b-ab06-4942b8c38ba6)
26.01.2022 09:49:27 -  will perform tests on Test Object 'pre17825481996620656117.xml' by using Executable Test Suite 'LAZY.8222c253-8468-4b94-a46b-2d1af1698a65'
26.01.2022 09:49:27 -  with parameters: 
26.01.2022 09:49:27 - etf.testcases = *
26.01.2022 09:49:27 -  TestTask 9 (b1f255ad-547c-487e-90f7-62af3e410a8c)
26.01.2022 09:49:27 -  will perform tests on Test Object 'pre17825481996620656117.xml' by using Executable Test Suite 'Conformance class: Application schema, Protected Sites Simple (EID: 4c53a8c7-7cac-4531-982b-d03eb48ffa77, V: 0.2.1 )'
26.01.2022 09:49:27 -  with parameters: 
26.01.2022 09:49:27 - etf.testcases = *
26.01.2022 09:49:27 -  TestTask 10 (f1c2fc8b-4433-419f-ba3f-3ba7ae5f1ccd)
26.01.2022 09:49:27 -  will perform tests on Test Object 'pre17825481996620656117.xml' by using Executable Test Suite 'Conformance class: Data consistency, Protected Sites (EID: 7831c8b4-f666-4534-838a-137b30bfecbe, V: 0.2.0 )'
26.01.2022 09:49:27 -  with parameters: 
26.01.2022 09:49:27 - etf.testcases = *
26.01.2022 09:49:27 - Test Tasks prepared and ready to be executed. Waiting for the scheduler to start.
26.01.2022 09:49:27 - Setting state to CREATED
26.01.2022 09:49:27 - Changed state from CREATED to INITIALIZING
```

Any ideas on what can cause this behaviour? A possibility we've considered is that the data consistency conformance class test depends on external resources which cannot be loaded for some reason. Can anyone confirm this?

**Comment by jenriquesoriano** [comment] 2022-01-28 15:10
Dear @hwbllmnn ,

thank you for pointing the issue. 
In order to proper analyze the actual cause, we would need a sample file or url that provokes this behaviour.
Could you please provide us with this info?

Thanks for your collaboration.

Best regards,

**Comment by hwbllmnn** [comment] 2022-02-01 09:30
Hi,

here's the test data:

[ps.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7977267/ps.zip)

Thanks

**Comment by jenriquesoriano** [comment] 2022-02-01 14:14
Dear @hwbllmnn  , 

we have tested your input data against staging and production instance, but the test has been completed correctly.
Please see: 
- PRODUCCIÓN
-- https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EID9d0e8a4e-556b-4d3f-bc32-49f805fbce33/log
- STAGING
-- http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/TestRuns/EID83955910-617a-4099-9b08-a5e08e8aeb0d/log

As you comment this issue can be caused by unavailabilities of external resources that may lead to that behaviour.
Please let us know if the issue persist.

Best regards,

**Comment by fabiovinci** [comment] 2022-07-05 09:29
Dear @hwbllmnn,

could you please confirm that the issue is no longer present?

**Comment by hwbllmnn** [comment] 2022-07-11 06:53
Hi @fabiovinci ,

the issue is not present any more when running the ETF locally with our patches against the code and our patches against the ETS to use local resources.

If the problems still persist with the unpatched versions I do not know, but would guess yes.

**Comment by fabiovinci** [comment] 2022-07-11 07:45
Dear @hwbllmnn,

thank you for your feedback, I re-tested your dataset in production and the test has been completed correctly (https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID507d2576-5533-480f-8ea3-8eaefbf0c5d4).

I'm closing the issue, please reopen or open a new one if the problem persists.

**Closed as completed by fabiovinci** 2022-07-11 07:45 UTC
Labels: question
