### ISSUE TITLE
XML document 'SpatialPlan.gml': -1:-1: Premature end of file.

### ISSUE THREAD

**Issue by jesperschmidt** [INSPIRE-MIF/helpdesk-validator#312] opened 2020-05-15 07:00 UTC
I started to get the following validation error on a running system on 12 may 2020 at about 18:00:

test: Conformance Class 'INSPIRE GML application schemas'
XML document 'SpatialPlan.gml': The file has 2 schema validation error(s).
XML document 'SpatialPlan.gml': -1:-1: Premature end of file.
XML document 'SpatialPlan.gml': -1:-1: Premature end of file.

The validation succeeded earlier on the 12 may 2020, and when i use the official JRC deployment the validation succeeds.

[SpatialPlan.gml.txt](https://github.com/inspire-eu-validation/community/files/4632732/SpatialPlan.gml.txt)

I think the problem is related to the xsd schemas. The 'planend land use' theme uses http in the schemalocation but the http is redirected to https and i think this is the cause of the problem.
I have tried to change the header in my gml to use https in the schemalocation. This causes a timeout in the validation. Also, the sub-xsd (base and base2) uses the http and not the hppts.

I have seen this problem mentioned earlier but that was back in 2017.
The problem also seems to exists in the latest version of the validator (v2020.1.2 15/04/2020)
I have attached a sample file (.txt was added to allow attaching the file).

**Comment by danielnavarrogeo** [comment] 2020-05-15 07:35
Dear @jesperschmidt 

We will analyze the issue and keep you posted.

Regards

**Comment by JohannaOtt** [comment] 2020-05-19 13:23
Probably related to the issue described here: https://github.com/deegree/deegree3/issues/1064
Just ran into the same issue with a different schema (INSPIRE ProductionFacility fixed version). Happens in productive and in staging system. Yesterday, I could sucessfully test data (again using a different schema though - INSPIRE Geology)

**Comment by JohannaOtt** [comment] 2020-05-19 14:17
I just tried again - it worked once: https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDb664557f-7149-4c5b-bba9-306b6798bf5d.html
But when I tried to reproduce the successful test report, it failed again with the behavior described above.

**Comment by jesperschmidt** [comment] 2020-06-03 12:54
I tested again, and this time i get a different result. The error have changed to not being able to access the codelist values on my local setup but still works fine on the official validator. The problem still seems to be that the codelist-urls are using http but are redirrected to https.
I have attached the validation report for the file attached above
[Test run on 1442 - 03.06.2020 with test suite Conformance class INSPIRE GML application schemas General requirements.html.txt](https://github.com/inspire-eu-validation/community/files/4723386/Test.run.on.1442.-.03.06.2020.with.test.suite.Conformance.class.INSPIRE.GML.application.schemas.General.requirements.html.txt)

**Comment by iuriemaxim** [comment] 2020-10-09 23:16
@jesperschmidt I downloaded the file, removed the .txt and tested on staging environment against the conformance class 'INSPIRE GML application schemas - General requirements (http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

No errors are provided:

http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID7d2e4c2c-e656-4019-90b9-4ac98e4c05ea.html

![image](https://user-images.githubusercontent.com/20813598/95638634-fca8db80-0a9d-11eb-96c1-b9cc62760c90.png)

**Comment by JohannaOtt** [comment] 2021-01-15 08:42
It happened to me again today in this test run https://inspire.ec.europa.eu/validator/v2/TestRuns/EID119e809d-24f6-41ee-bd24-40307aeeb60d.html with a fixed version of the EnvironmentalManagementFacilities schema

![grafik](https://user-images.githubusercontent.com/34163838/104702095-ccfd1580-5715-11eb-9292-0062213641b6.png)

**Comment by iuriemaxim** [comment] 2021-01-15 08:56
@JohannaOtt At least http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/ seems to be down right now. I tested on production the file that was provided by @jesperschmidt and no error is provided.
https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDe6d64d64-3110-4c70-816a-3389bb980f71.html
If sometimes works and sometime does not work, then it is a problem of communication between different components of the validator (incl. schemas retrieval).
![image](https://user-images.githubusercontent.com/20813598/104705092-266b4180-5722-11eb-96ef-29abbdbe5ecf.png)

**Comment by JohannaOtt** [comment] 2021-01-15 09:14
@iuriemaxim It also happened at the second try https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDeb10add1-1fa3-4154-b9b1-2a5eb61e76d2.html
This is the file: 
[testExport.zip](https://github.com/inspire-eu-validation/community/files/5819486/testExport.zip)

**Comment by iuriemaxim** [comment] 2021-01-15 09:56
@JohannaOtt The problem can be probably related to:
- communication delay due to necessary communication between validator and your server where you store the schemas. It is clear that your schemas will never be cached by the validator, but of course that a mechamism could be put in place to retieve your schema locally prior to test.
- the fact that your schema is starting with https, while the INSPIRE schema is starting with http.

In order to address the issue, you may replace:
https://wetransform.box.com/shared/static/14mz99bh6lmnecheyf07qyvgd3mvsujc.xsd 
with
http://inspire.ec.europa.eu/schemas/us-emf/4.0/EnvironmentalManagementFacilities.xsd
in the header of the file, within xsi:schemaLocation declaration

The file will look like the following one:
[testExportIM.zip](https://github.com/inspire-eu-validation/community/files/5819685/testExportIM.zip)

I am not in favor of declaring other schemas than the INSPIRE ones, located at ”inspire.ec.europa.eu/schemas/”, as this is most probably raising an interoperability issue for european users. Probably for local users is better, but for european ones is not.

If you will perform the test, then it will look like this one
https://inspire.ec.europa.eu/validator/v2/TestRuns/EID0b918c9c-ae2d-43dc-8e20-444b75a19d5e.html

You will see that other issues will be reported:

_The dataset has 1 file(s) with errors for this assertion.
XML document 'testExportIM.gml': The file has 59 schema validation error(s).
XML document 'testExportIM.gml': 26:118: cvc-complex-type.2.4.d: Invalid content was found starting with element 'us-emf:type'. No child element is expected at this point._

Of course you may try to modify your server to store the schemas under http, not under https, to see if this is the problem or not. If so, then will be more clear for @carlospzurita what can be done in the validator to address the issue.

Hope it helps.

**Comment by JohannaOtt** [comment] 2021-01-15 10:34
Hi Iurie,

Thanks you for your quick replies

> I am not in favor of declaring other schemas than the INSPIRE ones, located at ”inspire.ec.europa.eu/schemas/”, as this is most probably raising an interoperability issue for european users. Probably for local users is better, but for european ones is not.

We are usually using the INSPIRE schemas. In this case, we are using our own because there is an error in the INSPIRE one.
I will review it once more - thanks for the hint.

**Comment by iuriemaxim** [comment] 2021-01-15 13:49
> We are usually using the INSPIRE schemas. In this case, we are using our own because there is an error in the INSPIRE one.

Than I spupose that you may/should report that there is an error in INSPIRE schema as part of the testing of the data specification on Environmental Management Facilities (if ATS/ETS was published).

**Comment by JohannaOtt** [comment] 2021-01-15 15:27
> Than I spupose that you may/should report that there is an error in INSPIRE schema as part of the testing of the data specification on Environmental Management Facilities (if ATS/ETS was published).

The issue is known in the INSPIRE Forum - so I assume it will be fixed in the original schema one day https://inspire.ec.europa.eu/forum/file/view/217653/correction-of-the-schema-httpinspireeceuropaeuschemasus-emf40environmentalmanagementfacilitiesxsd

> And here the errors:
> The dataset has 1 file(s) with errors for this assertion.
> XML document 'testExportIM2.gml': The file has 5 schema validation error(s).
> XML document 'testExportIM2.gml': http://wetransform.box.com/shared/static/14mz99bh6lmnecheyf07qyvgd3mvsujc.xsd, 2:23: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '302 Found'.
> XML document 'testExportIM2.gml': http://wetransform.box.com/shared/static/14mz99bh6lmnecheyf07qyvgd3mvsujc.xsd, 4:22: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '302 Found'.
> XML document 'testExportIM2.gml': http://wetransform.box.com/shared/static/14mz99bh6lmnecheyf07qyvgd3mvsujc.xsd, 5:18: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw 'nginx'.
> XML document 'testExportIM2.gml': http://wetransform.box.com/shared/static/14mz99bh6lmnecheyf07qyvgd3mvsujc.xsd, 6:3: The element type "hr" must be terminated by the matching end-tag "".
> XML document 'testExportIM2.gml': http://wetransform.box.com/shared/static/14mz99bh6lmnecheyf07qyvgd3mvsujc.xsd, 6:3: The element type "hr" must be terminated by the matching end-tag "".

Concerning the error messages: I could reproduce them and I am surprised by what they state as there is no "hr" element occurring in the schema. I will clarify with my colleagues if anyone can come up with an idea what those might be caused by.

**Comment by JohannaOtt** [comment] 2021-01-15 16:02
In case anyone else is having similar issues: It helped to move the schema to a URL that is not using any redirects.

**Comment by fabiovinci** [comment] 2022-09-06 09:33
Dear @jesperschmidt,

the reported error is no more present, I validated your dataset against the related application schema (Planned Land Use) and the only three errors present seem right.

Attache the test report: 
[Test run on 11_06 - 06.09.2022 with test suite Annex III - Land Use (LU) - IOS 312.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9495344/Test.run.on.11_06.-.06.09.2022.with.test.suite.Annex.III.-.Land.Use.LU.-.IOS.312.zip)

I'm closing the issue, please reopen it or open a new one if the problem persists.

**Closed as completed by fabiovinci** 2022-09-06 09:33 UTC
